### ISSUE TITLE
Add .net core 3 support

### ISSUE THREAD

**Issue by Nithin-Mahendran** [okta/okta-aspnet#100]
This SDK does not work dotnet core 3.0. Can we have the SDK build for the newer version of dotnet?

**Comment by Zzarek** [comment]
@Nithin-Mahendran 

I have it running in .net core 3, but I had to make disable the new EndpointRouting functionality. 

Within configure services:

`            services.AddMvc(options => { options.EnableEndpointRouting = false; }).SetCompatibilityVersion(CompatibilityVersion.Version_3_0);
`

Then disable the routing and use "app.UseMvc();" in the configure method.

So while this makes it behave like .net core 2, and is far less than ideal, I hope it allows you to move forward. 

As a part of this feature, I would request that Okta support endpoint routing, as the above code is a deprecated feature that will only be supported by Microsoft for a short time.

**Comment by laura-rodriguez** [comment]
@Nithin-Mahendran 

I need to discuss the priority of this issue with the team since we are currently focused on other .NET projects, but this is definitely something we want to support.

In the meantime, are you able to use OIDC middleware so you're not blocked?

**Comment by Thialala** [comment]
Hello @laura-rodriguez ,

Any updates about supporting .NET Core 3 ? 

Thanks!

**Comment by laura-rodriguez** [comment]
Hi @Thialala ,

I will start looking into it next week. Stay tuned for updates :).

**Comment by laura-rodriguez** [comment]
Fixed by #103
