### ISSUE TITLE
Token expiration - Opera Web Browser

### ISSUE THREAD

**Issue by fzavalloni** [okta/okta-aspnet#109]
Hi,

An end user told us that his session in the application never expired. The first thing I did was try to replicate the issue.
I have tested with Chrome, Firefox and Edge and worked perfectly. However the end user uses an Opera Web Browser(https://www.opera.com/) and indeed when I access an application using this browser the session never expires. I remained authenticated forever what is a security flaw, because if I revoke its access the application access remain working.
The application is a ASP.NET MVC Core 2.2 and Okta.AspNetCore 1.1.5.
I have tested the token in the Okta Portal and the token expiration attributes looks correct.
  "iat": 1579862469,
  "exp": 1579866069,
Did someone experience any issue like this?

**Comment by laura-rodriguez** [comment]
Hi @fzavalloni,

The Okta SDK helps you with the authentication process. Once a local session is created in your application is up to you to invalidate that session. 

Do they remain authenticated even after logging out? What's the use case?

**Comment by laura-rodriguez** [comment]
Closed due to inactivity.
