### ISSUE TITLE
Override DefaultTokenValidationParameters

### ISSUE THREAD

**Issue by Zasuk** [okta/okta-aspnet#111]
Hi, 

I'm working in a project that contains 2 different apps (iOS Native App,Web App) and a middleware.
Both apps need to login using Okta SDK and then call some endpoints in the middleware, that should take the access token and validate it also using the Okta SDK.

The problem is that i get different audiences from both apps...
in the iOS app i get `api://default` but in the web app i get the ClientId and i can't find a way to make both work.

What can i do to fix this? is it possible to expose **DefaultTokenValidationParameters** and let user override some of the values?

**Comment by laura-rodriguez** [comment]
Hi @Zasuk ,

Thanks for your question.

Can you please help me to understand your use case? It's not clear to me how you use the Okta ASP.NET SDK in your iOS Native application. Also, what type of application is your Web App?

Is your use case related to this issue: https://github.com/okta/okta-aspnet/pull/99 ?

**Comment by Zasuk** [comment]
Hi @laura-rodriguez ,
i just found the problem...i was using the `id_token` instead of `access_token`

someone helped me here:
[](https://devforum.okta.com/t/validate-okta-audience/8052)
