### ISSUE TITLE
Support Auth code flow 

### ISSUE THREAD

**Issue by benaread** [okta/okta-aspnet#112]
We use .Net 4.6.1 MVC and have seen that only the hybrid flow is supported and the response type is hard coded into the response.

Can you introduce a new feature to support the auth code flow so we follow OKTA's own best practises of avoiding the hybrid flow where possible.

Details on package set-up below:

Thanks in advance.

` <package id="Okta.AspNet" version="1.4.0" targetFramework="net461" />`
 ` <package id="Okta.AspNet.Abstractions" version="3.0.2" targetFramework="net461" />`
`  <package id="Okta.Sdk" version="1.4.1" targetFramework="net461" />`
Sample Application setup OKTA documentation that we follow is here - https://developer.okta.com/quickstart/#/okta-sign-in-page/dotnet/aspnet4
 
Line of code where the response type is hardcoded to “code id_token” in the SDK – Line no 50 in the class BuildOpenIdConnectAuthenticationOptions -
https://github.com/okta/okta-aspnet/blob/master/Okta.AspNet/OpenIdConnectAuthenticationOptionsBuilder.cs

![image](https://user-images.githubusercontent.com/1142731/75695740-7116d300-5ca2-11ea-84e9-c6fb56961a9b.png)

**Comment by laura-rodriguez** [comment]
Hi @benaread ,

We have this task in our backlog already, and planning to work in this soon.

Thanks!

**Comment by benaread** [comment]
@laura-rodriguez , thanks for the quick update Laura, much appreciated!  Do you have any high level idea of when this will be worked on so i can update our schedules?

Thanks again, Ben

**Comment by laura-rodriguez** [comment]
Hi Ben,

We don't have a specific release date to share right now, but we expect to have it available as soon as we can.

**Comment by laura-rodriguez** [comment]
Fixed by #117
