### ISSUE TITLE
Example to allow multiple Audiences

### ISSUE THREAD

**Issue by ashishmundrajll** [okta/okta-aspnet#113]
Our API should allow access to a client with Audience id = 0oa***********0h7. The API should also allow another client with Audience Id = 0oapv************h7. 

However, AddOktaWebApi only takes one Audience as input. How can my API allow multiple Audiences? A sample code will be useful. 

Thanks.

**Comment by laura-rodriguez** [comment]
Thanks for writing this @ashishmundrajll !

I would like to understand your use case better. Can you please give me more details of why do you need to manage multiple audiences?

**Comment by ashishmundrajll** [comment]
@laura-rodriguez We like our API to be called from client and also from our API Gateway UI which has another client id. Hence API should allow both Audiences. Thanks.

**Comment by laura-rodriguez** [comment]
You can now configure the authentication type for both WebAPi and MVC apps which enables the multitenancy scenario:

public void Configuration(IAppBuilder app)
        {
            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies",
                CookieManager = new Microsoft.Owin.Host.SystemWeb.SystemWebChunkingCookieManager()
            });
                
            app.UseOktaMvc("tenant1", new OktaMvcOptions
            {
                // Replace these values with your Okta configuration
                OktaDomain = "myOktaDomain1",
                ClientId = "myClientId1",
                ClientSecret = "myClientSecret1",
                Scope = new List<string> { "openid", "profile", "email" },
                RedirectUri = "https://localhost:44314/oidc-signin-tenant1/callback"
            })
            .UseOktaMvc("tenant2", new OktaMvcOptions
            {
                // Replace these values with your Okta configuration

                OktaDomain = "myOktaDomain2",
                ClientId = "myClientId2",
                ClientSecret = "myClientSecret2",
                Scope = new List<string> { "openid", "profile", "email" },
                RedirectUri = "https://localhost:44314/oidc-signin-tenant2/callback"
            });
        }
Check out [Okta.AspNet 3.0.0](https://www.nuget.org/packages/Okta.AspNet/3.0.0) or [Okta.AspNetCore 4.2.0](https://www.nuget.org/packages/Okta.AspNetCore/4.2.0) for .NET Core 3+/.NET 5+.
