### ISSUE TITLE
.NET Core Authentication with cookies - MVC App

### ISSUE THREAD

**Issue by gituser22kk** [okta/okta-aspnet#114]
We use .NET Core 2.2 and our APIs to authenticate users (internally we use Okta's C# SDK to make calls to Okta to authenticate and generate Access and ID tokens). The web client only calls our APIs... they don't call Okta API directly. We don't use sign in widgets or Okta's portal to login users. 

We want to protect some parts of our application (for example anchor links/forms submissions) using cookies. We were successfully able to generate tokens and authenticate using jwt bearer tokens ... but using the generated access token with cookies isn't working. Is there any equivalent of "AddOktaWebApi" for cookies that we can use to protect MVC and other API servers?

Thank you!

**Comment by laura-rodriguez** [comment]
Hi @gituser22kk ,

Thanks for your question.

I have some follow-up questions to understand your use case better:

* When you say: _internally we use Okta's C# SDK_, what SDK do you mean? Okta.AspNetCore? Can you give me more details of your login process?
* Do you have both, a Web App MVC and Web API app that you want to protect?
* What exactly do you mean by protecting your application using cookies?

Also, in case you didn't check them yet, here you can find samples for .NET Core 2.x:
* https://github.com/okta/samples-aspnetcore

**Comment by gituser22kk** [comment]
Hello,
Thanks for your reply. Please see reply below. ***
> Hi @gituser22kk ,
> 
> Thanks for your question.
> 
> I have some follow-up questions to understand your use case better:
> 
> * When you say: _internally we use Okta's C# SDK_, what SDK do you mean? Okta.AspNetCore Can you give me more details of your login process?
*** Yes, we use all 3 Okta's sdk (ie.okta-sdk-dotnet, okta-auth-dotnet and okta-aspnet). Our website is asp.net core MVC and the client-side app is developed in Angular. The Angular app calls a dedicated API server which in turn uses above sdks to authorize; and sends the auth/id token back to the Angular app. The Angular app from that point sends the bearer token (with each request) to the Web API server, which works fine. The issue is to protect the MVC app using cookies as detailed below

> * Do you have both, a Web App MVC and Web API app that you want to protect?
*** Yes, that's right. But they are both on separate servers.

> * What exactly do you mean by protecting your application using cookies?
*** The MVC application needs to be protected using cookies since some of the resources are accessed directly with anchor links. The Angular app receives the jwt auth token from APP server  and saves it in a cookie (named "authCookie1", for example). For each call to MVC , the Angular app also sends the cookie... and we aren't sure how to protect the MVC app using this cookie.
> 
> Also, in case you didn't check them yet, here you can find samples for .NET Core 2.x:
> 
> * https://github.com/okta/samples-aspnetcore
*** Yes, we looked at them. However, we aren't using OIDC (MVC Challenge to redirect users). The user's aren't logging directly to Okta's portal. All the authentication goes through our app server as detailed above.

Thank you!

**Comment by laura-rodriguez** [comment]
Hi @gituser22kk ,

Thanks for providing more details.

I suggest reaching out to our support team (developers@okta.com).  They can examine the details of your particular use case and suggest solutions.

**Comment by gituser22kk** [comment]
We did reach out to the support team but didn't get solution for this particular use case. In short, how to protect an MVC app with a cookie stored on the client with Okta's access token in it. . Is there any equivalent of "AddOktaWebApi" for cookies?

Thank You!

**Comment by laura-rodriguez** [comment]
Hi @gituser22kk ,

I believe you can try with the `AddAuthentication` extension method. It allows you to configure different authentication schemas. You can take a look at the self-hosted sample where we had to configure Cookies as the default Authentication schema: https://github.com/okta/samples-aspnetcore/blob/master/samples-aspnetcore-3x/self-hosted-login/okta-aspnetcore-mvc-example/Startup.cs#L25. Does it help?

**Comment by laura-rodriguez** [comment]
Closed due to inactivity.
