### ISSUE TITLE
Error when using Org Authserver

### ISSUE THREAD

**Issue by brandongblack** [okta/okta-aspnet#115]
It seems by default this SDK supports using custom authServer. If a customer is using the org authServer is there a way to have it use that URL instead?  We are getting an error the following error:

IOException: IDX20807: Unable to retrieve document from: 'https://{{org}}.okta.com/oauth2/default/.well-known/openid-configuration'. HttpResponseMessage: 'StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:

I believe this is because by default this app is coded to route to:
 https://org.okta.com/oauth2/{{authserverID}}/.well-known/openid-configuration
(This URL will always return 401 in our case because the org is not licensed for this feature)

But we need this:
https://org.okta.com/.well-known/openid-configuration

It would be nice to have a flag to allow for "org" auth server vs "custom" authserver since the metadata URLs are indeed different

**Comment by laura-rodriguez** [comment]
Hi @brandongblack ,
You can specify the org AS in the following way:
```
.AddOktaMvc(new OktaMvcOptions
           {
               
                // Replace these values with your Okta configuration
                OktaDomain = Configuration.GetValue<string>("Okta:OktaDomain"),
               ClientId = Configuration.GetValue<string>("Okta:ClientId"),
               ClientSecret = Configuration.GetValue<string>("Okta:ClientSecret"),
               AuthorizationServerId = "", // Use org AS
               OnTokenValidated = OnTokenValidatedAsync,
           });
```

Let me know if it helps.

**Comment by brandongblack** [comment]
Hi yes that did the trick! Thank you for the help

**Comment by gtwilliams03** [comment]
I am trying to use this package with a WebApi - and I would like to use our Org auth server for access token issuance and to secure the routes of our API.  I tried to follow this example and leave the `AuthorizationServerId` property blank like above, but this command throws an error if the `AuthorizationServerId` is `null` or blank (`""`):

```
app.UseOktaWebApi(new OktaWebApiOptions
{
    OktaDomain = ConfigurationManager.AppSettings["Okta:Domain"],
    AuthorizationServerId = ""
});

```

It throws this exception:

```
System.ArgumentException
  HResult=0x80070057
  Message=The Org Authorization Server is not supported.
Parameter name: AuthorizationServerId
  Source=Okta.AspNet.Abstractions
  StackTrace:
   at Okta.AspNet.Abstractions.OktaWebApiOptionsValidator.ValidateInternal(OktaWebApiOptions options)
   at Okta.AspNet.OktaMiddlewareExtensions.UseOktaWebApi(IAppBuilder app, OktaWebApiOptions options)
   at Startup.Configuration(IAppBuilder app) in <REMOVED>\Startup.cs:line 72

```

**Comment by gtwilliams03** [comment]
Never mind.

> Note: [The Org Authorization Server](https://developer.okta.com/docs/concepts/auth-servers/#org-authorization-server) is not supported for Web API because the access token issued by this Authorization Server cannot be validated by your own application. Check out the [Okta documentation](https://developer.okta.com/docs/concepts/auth-servers/#org-authorization-server) to learn more.
