### ISSUE TITLE
WWW-Authenticate Error

### ISSUE THREAD

**Issue by RealDotNetDave** [okta/okta-aspnet#125]
We have added the OKTA ASP.NET Core package to our project and set it up as per the OKTA documentation. After some issues, we are now seeing this error come back from a call to our API.

`WWW-Authenticate header field containing a challenge applicable to the requested resource.`

Does anyone know how to fix this?

**Comment by laura-rodriguez** [comment]
Hi @RealDotNetDave ,

Thanks for your question! 

Would you mind answering a few questions? This info will help us to understand your use case better :).

* Is your project a Web API or MVC application? What's your use case?
* Can you share what Okta documentation are you following?
* What .NET Core version and Okta.AspNetCore are you using?
* When exactly are you seeing this issue (for example, _right after I sign in_ or _when I call a protected endpoint in my app_)?

Thanks!

**Comment by RealDotNetDave** [comment]
Thanks, Laura for the response. Here are the answers to your questions:

1. It's a .NET Core Web API Project.
2. I followed the documentation here: (https://github.com/okta/okta-aspnet/blob/master/docs/aspnetcore-webapi.md)
3. We are using .NET Core 3.1 and version 3.1.1 of the Okta package.
4. We see the error from the response from our API.

Our team is meeting about this right now.
David

**Comment by laura-rodriguez** [comment]
Thanks for your response @RealDotNetDave .

How are you obtaining the access token that you are passing to your Web API app? Also, are you using the Okta Org Authorization Server or the Default one? If you are not sure, you can check out the following link: https://developer.okta.com/docs/concepts/auth-servers/

**Comment by RealDotNetDave** [comment]
Thanks for reaching out. We got Okta working for our product that we released a few weeks ago.

David

**Comment by laura-rodriguez** [comment]
Hi @RealDotNetDave !

I'm glad you got it working. May I ask you what the issue was?
