### ISSUE TITLE
Callback Nonce validation error in Chrome with console message "SameSite attribute was not set or is invalid"

### ISSUE THREAD

**Issue by gbraymondwk** [okta/okta-aspnet#139]
## Current behavior

This is in dev for a new version of our internal Asp.Net MVC app, and last week it started reporting the following error every time I try to start the app in Chrome when it is processing the Callback. This happens on my development desktop when I start in Visual Studio, and it also happens when starting the app when it is deployed to our staging server.
"IDX21323: RequireNonce is 'True'. OpenIdConnectProtocolValidationContext.Nonce was null, OpenIdConnectProtocol.ValidatedIdToken.Payload.Nonce was not null. The nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'. Note if a 'nonce' is found it will be evaluated.
"

There is also a message in the Chrome Developer Console that:
"Because a cookie's SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being sent in a cross-site request. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.

Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests
"
It looks like Chrome may be preventing the security cookie from being passed through.

I updated all of the Okta and Microsoft.IdentityModel DLLs to the latest versions (Okta to 1.7.0.0 and MS to 6.7.1), but the problem is still there.
Edge and Firefox work fine, but unfortunately nearly everyone in our company uses Chrome.

## Expected behavior

Complete the Callback without errors.

## Minimal reproduction of the problem with instructions

This happens as soon as I start the app. The app is written to use Okta to authorize all requests from the browser, and so this error is being hit before any processing happens for the initial page.

## Environment

- OS: Windows 10 Enterprise and Windows Server 16
- Browser: Chrome 84.0.4147.105 (Official Build) (64-bit)

- .Net Framework: 4.7 Framework (not Core, not Standard)

- Other:

This just started happening to me last week (roughly July 27th). I hadn't changed any of our Okta code in Startup.cs before the problem started. The startup code is nearly identical to the examples on your developer's site, and I have tried changing specific lines to make it the same, but with no change in behavior.

**Comment by laura-rodriguez** [comment]
Hi @gbraymondwk,

This seems to be related to the SameSite changes that the latest version of Chrome has introduced.

By default, the nonce cookie should be marked as secure if you are using https unless you have some sort of configuration or a proxy that is preventing this. 

I suggest looking into the workarounds suggested by MS that should be done at the application level: https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

I hope this helps.

**Comment by gbraymondwk** [comment]
Thanks for the confirmation. We are not currently using certs/https on our
dev desktops or our staging server, and so the "Secure" part with SameSite
is likely what's tripping up our authorization on those platforms and why
our production site running a slightly older version of our app but *with*
HTTPS hasn't had any issues.

Greg

**Comment by laura-rodriguez** [comment]
Hi Greg,

I think that's the main purpose of this change, to enforce apps to use https.

I suggest looking into [this issue](https://github.com/dotnet/aspnetcore/issues/19939). I know it's ASP.NET Core, but the issue is the same.
