### ISSUE TITLE
Allow setting absolute url for CallbackPath 

### ISSUE THREAD

**Issue by simplecoder** [okta/okta-aspnet#140]
The okta middlware allows setting a CallbackPath, but seems to only allow relative urls. If I specify an absolute url i get this error - `ArgumentException: The path in 'value' must start with '/'. (Parameter 'value')` I am wondering can we allow for absolute urls or is there some option within the parameters to always make sure the redirect_uri is set in https instead of http?

**Comment by bryanapellanes-okta** [comment]
@simplecoder ,
Thank you for submitting this issue. We will review internally to determine the appropriate approach to achieve what you're requesting. We'll respond here when more information is available. Stay tuned!

Thanks!
Bryan

**Comment by laura-rodriguez** [comment]
Hi @simplecoder,

May I ask what's the use case here? If your app is using https, the CallbackPath should be using https as well.

Can you describe the steps to reproduce the issue you are running into?

**Comment by simplecoder** [comment]
Well in this specific case, the app is running in a kubernetes cluster in http. The SSL termination happens at the cluster level and forwards the request to the http app. The app is redirecting to Okta and we need the redirect uri to say https even though the app internally is running as http.

**Comment by bryanapellanes-okta** [comment]
@simplecoder,
Unfortunately, there is no way to do what you're asking within the Sdk; the CallbackPath value provided is delegated to the OpenIdConnect framework used internally.

You may have options using Kubernetes to rewrite the url within the cluster but that is beyond the scope of our Sdk.

**Comment by bill-robbins-ss** [comment]
@simplecoder did you find a solution to this? Running into the exact same issue

**Comment by bryanapellanes-okta** [comment]
This is related to #110 ; closing this issue in favor of #110.
