### ISSUE TITLE
401 Unauthorized Error on ASP.NET Web API

### ISSUE THREAD

**Issue by breannamporter** [okta/okta-aspnet#141]
I followed the tutorial linked here (https://developer.okta.com/quickstart/#/widget/dotnet/aspnet4) and my front end (an angular single page app) is successfully singing-in using the Sign-In Widget and the Auth Code Flow with PKCE but I am getting a 401 unauthorized error whenever I try to make requests to the .NET Framework 4.5.2 Web API which I secured by following the 'Server Setup' section in the same tutorial. 

I have been working with Okta support and have confirmed that the tokens being passed by my front end work fine with the sample APIs available on Okta's github and that my configuration looks correct so they encouraged me to open this github issue since we are still unable to determine the issue at play. I was able to get the following stack trace of the error by building the okta-aspnet project within my API. 

System.ArgumentNullException HResult=0x80004003 Message=Value cannot be null. Parameter name: source Source=Okta.AspNet StackTrace: at Okta.AspNet.OktaMiddlewareExtensions.<>c__DisplayClass2_0.<AddJwtBearerAuthentication>b__0(String token, SecurityToken securityToken, String keyId, TokenValidationParameters validationParameters) in C:\Users\BreannaPorter\Desktop\git\okta-aspnet\Okta.AspNet\OktaMiddlewareExtensions.cs:line 70 at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters) at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken) at Okta.AspNet.Abstractions.StrictTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken) in C:\Users\BreannaPorter\Desktop\git\okta-aspnet\Okta.AspNet.Abstractions\StrictTokenHandler.cs:line 27 at Microsoft.Owin.Security.Jwt.JwtFormat.Unprotect(String protectedText) at Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationHandler.<AuthenticateCoreAsync>d__3.MoveNext() 

Here is the function in which this exception is thrown: 
private static void AddJwtBearerAuthentication(IAppBuilder app, OktaWebApiOptions options) { var issuer = UrlHelper.CreateIssuerUrl(options.OktaDomain, options.AuthorizationServerId); var httpClient = new HttpClient(new OktaHttpMessageHandler("okta-aspnet", typeof(OktaMiddlewareExtensions).Assembly.GetName().Version, options)); var configurationManager = new ConfigurationManager<OpenIdConnectConfiguration>( issuer + "/.well-known/openid-configuration", new OpenIdConnectConfigurationRetriever(), new HttpDocumentRetriever(httpClient)); // Stop the default behavior of remapping JWT claim names to legacy MS/SOAP claim names JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear(); var signingKeyCachingProvider = new DiscoveryDocumentCachingSigningKeyProvider(new DiscoveryDocumentSigningKeyProvider(configurationManager)); var tokenValidationParameters = new DefaultTokenValidationParameters(options, issuer) { ValidAudience = options.Audience, IssuerSigningKeyResolver = (token, securityToken, keyId, validationParameters) => { return signingKeyCachingProvider.SigningKeys.Where(x => x.KeyId == keyId); //NOTE: Exception is thrown on this line }, }; app.UseJwtBearerAuthentication(new JwtBearerAuthenticationOptions { AuthenticationMode = AuthenticationMode.Active, TokenValidationParameters = tokenValidationParameters, TokenHandler = new StrictTokenHandler(), }); }

Let me know if I can provide any further information for you all!

**Comment by laura-rodriguez** [comment]
Hi @breannamporter ,

Sorry for the inconvenience.

Have you verified that you are using the same authorization server for both of your applications (SPA and Web API)? 

Can you also post a fiddler log that captures the moment you are hitting the protected endpoint in your Web API?

**Comment by breannamporter** [comment]
Hi @laura-rodriguez yes, they are both using the same authorization server. I will get back to you Monday with the Fiddler log.

**Comment by laura-rodriguez** [comment]
Hi @breannamporter , 

Can you also post your SPA configuration + your Web API configuration (Web.config + Startup), please? Don't forget to obfuscate your secrets ;).

**Comment by breannamporter** [comment]
SPA Configuration: 
```
self.oktaSignIn = new OktaSignIn({
        baseUrl: 'https://dev-779069.oktapreview.com',
        redirectUri: window.location.origin,
        clientId: '<REMOVED>',
        authParams: {
            pkce: true,
            responseMode: 'query',
            issuer: 'https://dev-779069.oktapreview.com/oauth2/default'
        }
    });
```

Web API Configuration: [APIConfig.zip](https://github.com/okta/okta-aspnet/files/5152420/APIConfig.zip)

From Fiddler:

Raw request
```
GET http://localhost:58057/api/1.0/ut/getSchool HTTP/1.1
Session-Key: f3ab12a2-dd0c-4f4e-89d0-ce4836bfe8f6
Authorization: Bearer <REMOVED TOKEN>
User-Agent: PostmanRuntime/7.26.3
Accept: */*
Cache-Control: no-cache
Postman-Token: 62d177db-db68-40b0-94e1-7211a167a2a9
Host: localhost:58057
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
```
Raw response
```
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/10.0
X-AspNet-Version: 4.0.30319
WWW-Authenticate: Bearer
X-SourceFiles: =?UTF-8?B?QzpcVXNlcnNcQnJlYW5uYVBvcnRlclxSZWFkQVBJXEFyY2hpbWVkZXMuUmVhZEFQSVxhcGlcMS4wXHV0XGdldFNjaG9vbA==?=
X-Powered-By: ASP.NET
Date: Mon, 31 Aug 2020 20:47:02 GMT
Content-Length: 61

{"message":"Authorization has been denied for this request."}
```
I know that the tokens being generated by my front-end are valid because I was able to test them using one of the sample APIs on okta's git.

**Comment by laura-rodriguez** [comment]
Thanks for the details @breannamporter .

Your configuration looks good to me. One minor comment, since you are using the `default` Authorization Server you can skip line 22 and 23 in your Startup because our SDK sets those default values for you. This is how it should look like:

```
app.UseOktaWebApi(new OktaWebApiOptions()
            {
                OktaDomain = ConfigurationManager.AppSettings["okta:OktaDomain"],
            });
```

Anyways, that shouldn't be an issue.

Can you also show me the protected method you are trying to call? Are you using the default `Authorize` attribute or you have a custom authorization attribute?

You mentioned you got it working using our Web API sample right? So, if you pass the same token you get via the SPA to the Web API sample using your org configuration, does it work?

**Comment by breannamporter** [comment]
Yep, Okta support suggested I add those declarations just to confirm it couldn't be contributing to my issue. 

Here is my WebApiConfig.cs code to answer your question about the authorize attribute:
```
using System.Web.Http;
using System.Web.Http.Cors;
using Newtonsoft.Json.Serialization;

namespace Archimedes
{
    /// <summary>
    /// Web config for API.
    /// </summary>
    public static class WebApiConfig
    {
        /// <summary>
        /// Registers configuration.
        /// </summary>
        /// <param name="config">HttpConfiguration</param>
        public static void Register(HttpConfiguration config)
        {
            // adding tracing
            config.EnableSystemDiagnosticsTracing();

            // Web API configuration and services
            config.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
            config.Formatters.Remove(GlobalConfiguration.Configuration.Formatters.XmlFormatter);
            config.Formatters.Add(GlobalConfiguration.Configuration.Formatters.JsonFormatter);

            // Requiring Authentication for all actions
            config.Filters.Add(new AuthorizeAttribute());

            // Web API routes
            config.MapHttpAttributeRoutes();

            // Enable CORS
            var cors = new EnableCorsAttribute("*", "*", "*");
            config.EnableCors(cors);

            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
        }
    }
}
```

and here is the getSchool method I've been testing with:
```
        #region GetSchools

        /// <summary>
        /// Gets schools associated to a user
        /// </summary>
        /// <returns></returns>
        [Route("getSchool")]
        [HttpGet]
        public async Task<HttpResponseMessage> GetSchool()
        {
            var principal = RequestContext.Principal.Identity as ClaimsIdentity;

            var response = await _iAotyReadInterface.HandleGetSchoolUserTool(Request, principal);

            return response;
        }

        #endregion GetSchools
```

Inn my testing, the error in the Okta SDK is thrown before any of the code within this method is hit (breakpoints added within this method are never hit when running the API locally). And yes, I am able to successfully make calls to the web api sample using my org configuration and the token generated by my SPA.

**Comment by laura-rodriguez** [comment]
Thanks, @breannamporter .

I just performed a quick test using the information you and support provided me, and I was able to hit a protected endpoint using my Org configuration.

I suggest performing the same steps to verify that everything is working as expected or try to narrow down the issue.

**Setup**

I used the following React sample for the front end: [Okta-hosted login](https://github.com/okta/samples-js-react/tree/master/okta-hosted-login).

Also, I added the following method to the `AotyUserToolReadController` controller that I have extracted from our Web API samples:

```
        [Route("~/api/messages")]
        [HttpGet]
        public IHttpActionResult Get()
        {
            var principal = RequestContext.Principal.Identity as ClaimsIdentity;

            var login = principal.Claims
                .SingleOrDefault(c => c.Type == System.IdentityModel.Claims.ClaimTypes.NameIdentifier)
                ?.Value;

            return Json(new
            {
                messages = new dynamic[]
                {
                    new { date = DateTime.Now, text = "I am a Robot." },
                    new { date = DateTime.Now, text = "Hello, world!" },
                },
            });
        }
```
I have changed the port of the Web API project to 8000 since that's the port that the React sample expects for retrieving messages.

I have referenced the Okta ASP.NET projects (Okta.AspNet and Okta.AspNet.Abstractions) instead of the NuGets so I could debug that the signing keys were successfully retrieved and cached. I have added a breakpoint [here](https://github.com/okta/okta-aspnet/blob/master/Okta.AspNet/DiscoveryDocumentSigningKeyProvider.cs#L33) to check that. 

**Things to verify**

1- As soon as you start the Web API project (even before hitting a protected endpoint) it should retrieve the signing keys from your Okta org that will eventually use to validate tokens. You can verify that with Fiddler:
![image](https://user-images.githubusercontent.com/16751130/91893896-d56f1b00-ec62-11ea-8b3a-dedf80e11ea8.png)
You can also update the code [here](https://github.com/okta/okta-aspnet/blob/master/Okta.AspNet/DiscoveryDocumentCachingSigningKeyProvider.cs#L53) to double-check that no exceptions were thrown during keys retrieval:

```
  // The keys retrieval runs in background. The IssuerSigningKeyResolver will always use the last known value, while periodically updating up.
            // This helps to prevent deadlocks. See https://github.com/aspnet/AspNetKatana/issues/363.
            ThreadPool.UnsafeQueueUserWorkItem(
                state =>
                {
                    try
                    {
                        RetrieveMetadata();
                    }
                    catch (Exception e)
                    {
                        //Add breakpoint here to check if an exception was thrown during keys retrieval
                        Console.WriteLine(e.Message);
                    }
                }, state: null);
```

2- When hitting the protected endpoint `api/messages` make sure that the signing keys were successfully cached. Add a breakpoint [here](https://github.com/okta/okta-aspnet/blob/master/Okta.AspNet/DiscoveryDocumentCachingSigningKeyProvider.cs#L34) and `_keys` shouldn't be null. 

![image](https://user-images.githubusercontent.com/16751130/91897276-0736b080-ec68-11ea-8254-22cfb81c21a0.png)

3- If keys were successfully cached the token validation should pass

4- Click the `Messages` link from the React sample to hit the protected endpoint and retrieve the messages

![image](https://user-images.githubusercontent.com/16751130/91897436-4b29b580-ec68-11ea-9e29-f381ac9d99d9.png)

**Additional notes**

I also hit the `GetSchool` method, and after passing the token validation the following line failed with 401:
```
var response = await _iAotyReadInterface.HandleGetSchoolUserTool(Request, principal);
```
So, make sure the 401 you are getting is not coming from that piece of code:

![image](https://user-images.githubusercontent.com/16751130/91898399-a5774600-ec69-11ea-817d-f0c99b2f4268.png)

Please let us know how it goes after following these steps.

cc @codepadma

**Comment by breannamporter** [comment]
Hi @laura-rodriguez thank you again for your help on this.  So it looks like the issue is in fact because the application is unable to retrieve the signing keys from okta. 

On the fiddler side, the only okta related activity I'm seeing are two requests one after the other, both of which are successful. 

1st raw request
```
CONNECT dev-779069.oktapreview.com:443 HTTP/1.1
User-Agent: os-version/Microsoft Windows NT 10.0.17134.0/Win32NT okta-aspnet/1.7.0
Host: dev-779069.oktapreview.com
x-ms-request-root-id: 6d299108-492f87a1627e6adc
x-ms-request-id: |6d299108-492f87a1627e6adc.
Request-Id: |6d299108-492f87a1627e6adc.
Connection: Keep-Alive

A SSLv3-compatible ClientHello handshake was found. Fiddler extracted the parameters below.

Version: 3.1 (TLS/1.0)
Random: 5F 4F B7 3F FF 03 27 12 64 51 B6 C0 E0 FF E8 3B 3F D1 86 9A BA 84 6F 7E 8F 86 72 97 69 F4 99 2E
"Time": 11/16/2003 5:20:15 AM
SessionID: empty
Extensions: 
	server_name	dev-779069.oktapreview.com
	supported_groups	x25519 [0x1d], secp256r1 [0x17], secp384r1 [0x18]
	ec_point_formats	uncompressed [0x0]
	SessionTicket	empty
	extended_master_secret	empty
	renegotiation_info	00
Ciphers: 
	[C00A]	TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
	[C009]	TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
	[C014]	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
	[C013]	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
	[0035]	TLS_RSA_WITH_AES_256_CBC_SHA
	[002F]	TLS_RSA_WITH_AES_128_CBC_SHA
	[000A]	SSL_RSA_WITH_3DES_EDE_SHA

Compression: 
	[00]	NO_COMPRESSION
```
1st raw response
```
HTTP/1.1 200 Connection Established
FiddlerGateway: Direct
StartTime: 11:16:15.806
Connection: close
EndTime: 11:16:15.839
ClientToServerBytes: 130
ServerToClientBytes: 0
```

2nd raw request
```
CONNECT dev-779069.oktapreview.com:443 HTTP/1.1
User-Agent: os-version/Microsoft Windows NT 10.0.17134.0/Win32NT okta-aspnet/1.7.0
Host: dev-779069.oktapreview.com
x-ms-request-root-id: 6d299109-492f87a1627e6adc
x-ms-request-id: |6d299109-492f87a1627e6adc.
Request-Id: |6d299109-492f87a1627e6adc.

A SSLv3-compatible ClientHello handshake was found. Fiddler extracted the parameters below.

Version: 3.1 (TLS/1.0)
Random: 5F 4F B7 3F F1 40 E5 E9 E5 FA EA 53 23 6F F4 C2 4E BA CB C6 BF 93 93 B0 8C D1 DB 91 B0 3E 0A 74
"Time": 11/16/2003 5:20:15 AM
SessionID: empty
Extensions: 
	server_name	dev-779069.oktapreview.com
	supported_groups	x25519 [0x1d], secp256r1 [0x17], secp384r1 [0x18]
	ec_point_formats	uncompressed [0x0]
	SessionTicket	empty
	extended_master_secret	empty
	renegotiation_info	00
Ciphers: 
	[C00A]	TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
	[C009]	TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
	[C014]	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
	[C013]	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
	[0035]	TLS_RSA_WITH_AES_256_CBC_SHA
	[002F]	TLS_RSA_WITH_AES_128_CBC_SHA
	[000A]	SSL_RSA_WITH_3DES_EDE_SHA

Compression: 
	[00]	NO_COMPRESSION
```

2nd raw response 
```
HTTP/1.1 200 Connection Established
FiddlerGateway: Direct
StartTime: 11:16:15.878
Connection: close
EndTime: 11:16:15.901
ClientToServerBytes: 130
ServerToClientBytes: 0
```

Per your suggestion, I updated the code [here](https://github.com/okta/okta-aspnet/blob/master/Okta.AspNet/DiscoveryDocumentCachingSigningKeyProvider.cs#L53) to examine the exception. See the screenshot below for details.  
<img width="1680" alt="Screen Shot 2020-09-02 at 11 41 18 AM" src="https://user-images.githubusercontent.com/25419454/92005236-3b19e080-ed11-11ea-9352-f34a15e54f7f.png">

Let me know what I can do to further pin down this issue. Thanks!

**Comment by bryanapellanes-okta** [comment]
@breannamporter,
I'm inquiring internally about the error message shown in the screenshot to get more insight into the issue.  Hopefully, I'll have more to share soon.

cc @laura-rodriguez

**Comment by bryanapellanes-okta** [comment]
@breannamporter,
While reviewing logs, we were unable to find entries related to the request whose details are shown in your latest comment above.  The error text implies that the server is receiving "System.String" where json is expected.  Can you confirm what implementation of `IDiscoveryDocumentSigningKeyProvider` is in use when this code executes https://github.com/okta/okta-aspnet/blob/master/Okta.AspNet/DiscoveryDocumentCachingSigningKeyProvider.cs#L70?

**Comment by breannamporter** [comment]
hi @bryanapellanes-okta see below for the implementation. 

```
// <copyright file="DiscoveryDocumentSigningKeyProvider.cs" company="Okta, Inc">
// Copyright (c) 2018-present Okta, Inc. All rights reserved.
// Licensed under the Apache 2.0 license. See the LICENSE file in the project root for full license information.
// </copyright>

using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.IdentityModel.Protocols;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using Microsoft.IdentityModel.Tokens;

namespace Okta.AspNet
{
    internal sealed class DiscoveryDocumentSigningKeyProvider : IDiscoveryDocumentSigningKeyProvider
    {
        private readonly ConfigurationManager<OpenIdConnectConfiguration> _configurationManager;

        public DiscoveryDocumentSigningKeyProvider(
            ConfigurationManager<OpenIdConnectConfiguration> configurationManager)
        {
            _configurationManager = configurationManager;
        }

        public async Task<IEnumerable<SecurityKey>> GetSigningKeysAsync()
        {
            var discoveryDocument = await _configurationManager.GetConfigurationAsync().ConfigureAwait(false);
            return discoveryDocument.SigningKeys;
        }

        public IEnumerable<SecurityKey> GetSigningKeys()
        {
            var discoveryDocument = _configurationManager.GetConfigurationAsync().Result;
            return discoveryDocument.SigningKeys;
        }
    }
}
```

**Comment by laura-rodriguez** [comment]
Hi @breannamporter,

Since you mentioned that it works correctly with our example (which is using v4.7) I wonder if this is an issue with .NET 4.5.

Can you please try targeting a newer framework in your application? I understand if this is not possible.

Another thing to try (without changing your framework target) is using an older version of the Okta SDK. We recently made a change in the way we get the signing keys to avoid deadlocks. Can you please use [`Okta.AspNet 1.5.0`](https://www.nuget.org/packages/Okta.AspNet/1.5.0) and try again?

**Comment by laura-rodriguez** [comment]
Closing now due to inactivity. Please, feel free to reopen if this is still an issue for you.
