### ISSUE TITLE
Add possibility to specify "login_hint" parameter

### ISSUE THREAD

**Issue by es-repo** [okta/okta-aspnet#142]
As I see from the documentation and from the source code there is no way to specify "login_hint" parameter.

Would be nice to have this feature or to provide access to `OpenIdConnectAuthenticationNotifications.RedirectToIdentityProvider` notification.

**Comment by laura-rodriguez** [comment]
Hi @es-repo,

Thanks for your suggestion.

As you well noticed, we don't expose that event at the moment, but we are planning to support this in the future since many people have reported needing access to OIDC events for their custom scenarios.

Stay tuned for updates!

**Comment by laura-rodriguez** [comment]
Hi @es-repo,

We have recently released a new version that allows you to pass the `login_hint_param`  during authentication. Check out [the readme](https://github.com/okta/okta-aspnet/blob/master/docs/aspnetcore-mvc.md#specifying-the-login_hint-parameter) for more details. 

We are still planning to expose OIDC in the future, so stay tuned for that.

Thank you!
