### ISSUE TITLE
AuthZ doc ideas for Web API

### ISSUE THREAD

**Issue by mfish0005** [okta/okta-aspnet#144]
## My Use Case
I'm evaluating Okta for managing my startup's users.  I'm building a multi-user app with Angular/Dotnet Core Web API.  Users will be able to do basic things like:

1. Register/log in
2. Create Content 
3. View other people's content
4. Manage *their own* content

## Summary
I've used Okta and this package to set up user registration/log in functionality for my startup by following the [Core Web Api Guide](https://developer.okta.com/docs/guides/protect-your-api/aspnetcore3/before-you-begin/) and [Angular Guide](https://developer.okta.com/docs/guides/sign-into-spa/angular/before-you-begin/).  

I have my front and back end authenticating successfully.  Users can register and log in from the Angular app and my API routes are protected by `[Authorize]` attributes.  My problem is I'm unsure how to implement multi user authorization.  I'm also not sure how to tie basic CRUD operations for each user in with Okta.

## Doc Ideas
The docs I've been able to find on Role/Policy based authorization are a bit outdated and are written for MVC: [Policy Based Auth Doc](https://developer.okta.com/blog/2018/05/11/policy-based-authorization-in-aspnet-core)  I'm unclear of how it would fit in with this package and my use case(SPA and Web API).  

I feel like a doc showing a more complex scenario of multi user authorization would be really helpful for me(and possibly others).  I wouldn't mind writing one later down the line if I figure out how to proceed with Okta.

**Comment by mfish0005** [comment]
After some further research I found this article which is fairly newer: https://developer.okta.com/blog/2020/06/10/crud-entity-framework-core

It answers some of my questions but uses an MVC approach.  It also doesn't reference this package.

**Comment by laura-rodriguez** [comment]
Hi @mfish0005 ,

Thank you so much for your feedback.

Can you please clarify what do you mean by multi-user authorization?

Also, can you please describe what would be the responsibility of your SPA vs the Web API project? Trying to get a better understanding of your use case here :).

**Comment by mfish0005** [comment]
Hey @laura-rodriguez !  Sorry it took me so long to respond.  Not long after I created this issue a forest fire started up the road from my house.  Was away from my machine during the evacuation.  

1. I think what I probably meant by multi-user authorization was more along the lines of role based or policy based authorization.  This is all very exploratory and I still haven't figured out which roles a user might have.  

2.  Sorry I was pretty vague about the app.  It's a fairly standard monolithic Web API with an Angular front end.  The SPA basically allows users to create, view, update, and delete posts.  The Web API is responsible for processing those CRUD operations.  Here is a simplified example: A user fills out a form to create a post using the SPA.  When the form is submitted it fires a POST request to a Web API endpoint like `http://localhost:5000/api/posts` with a JSON object containing something like this
```json
{ 
    id: 1, 
    title: "Some Post", 
    content: "Some big string containing post content"
}
```
Another problem I had was the best way to store that in the database in manner that allows me to retrieve it later for a specific user.   I would typically do something like attach a user id to it - but I'm unsure of whether I should use Okta's user id for this or create my own.

**Comment by laura-rodriguez** [comment]
Hi @mfish0005,

I'm sorry to hear there was a fire nearby, I hope everything's fine!

Thanks for the additional details, it's more clear now. I still have one more question though.
Where are you planning to implement role-based authorization? In the SPA or the Web API or maybe both? Can you give me an example of how it would work? 

Regarding the best way to store posts, it's up to you. There are many ways to do it, and you should choose the one that works better with your use case. You just need to make sure to link the Okta's user with your application user, for example, via custom attributes. For this particular question, I suggest asking in https://devforum.okta.com/ since you have a broader audience there that might have done this in the past.

**Comment by mfish0005** [comment]
Thanks @laura-rodriguez :) Luckily they have the fire under control now and the only damage was to the hill behind my house.

Both the SPA and API will probably need some sort of user role integration.  Here are some possible roles:

`Viewer`: In order to view posts a user needs to be logged in so I think all registered users should be assigned a `Viewer` role.   `Editor`: Users should only be able to edit their own posts *unless* they are a company admin.
`Company Member` Members of a company might have access to private content created by other company members
`Company Admin`: These users should be able to edit any posts created by members of their company. 
`Admin` and `Support`: I need a way to police the posts for inappropriate content so I think a role like this will be necessary.

This is all tentative stuff.  I think I need to take the time to draw up some design docs and flesh out my wireframes.  It's so much easier when those things are provided for me haha.
