### ISSUE TITLE
Okta sign-in and ASP.NET Identity compatibility issue

### ISSUE THREAD

**Issue by Giorgi** [okta/okta-aspnet#151]
## Current behavior
Sign in with Okta doesn't work together in ASP.NET Core web project with ASP.NET Identity

## Expected behavior
Sign in with Okta should work in ASP.NET Core project with ASP.NET Identity

Repro available at: [OktaAspNetIdentity Issue Repro](https://github.com/Giorgi/OktaAspNetIdentity)

## Environment

- OS: Windows 10
- .Net Core 3.1
- Other:

First, Sign in with Okta works in ASP.NET Core projects which **don't use** ASP.NET Identity. I followed steps at [
Sign users in to your web application](https://developer.okta.com/docs/guides/sign-into-web-app/aspnetcore3/before-you-begin/) and it works as expected.

But if I create a new project with **Individual User Account** 
![image](https://user-images.githubusercontent.com/580749/94147920-02d86e80-fe87-11ea-9f63-d284e7628b96.png)

and add `Okta.AspNetCore`  when I go to `Identity/Account/Register` I see the following screen:

![image](https://user-images.githubusercontent.com/580749/94148234-69f62300-fe87-11ea-84ab-74800f10830a.png)

When I click the `OpenIdConnect` button I'm redirected to Okta as expected but when I'm redirected back I get the following error:

![image](https://user-images.githubusercontent.com/580749/94148380-9c078500-fe87-11ea-9fd2-be7eca714a46.png)

On the other hand if I use the following package: [AspNet.Security.OAuth.Okta](https://www.nuget.org/packages/AspNet.Security.OAuth.Okta/) from [AspNet.Security.OAuth.Providers](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers) it works as expected.

So am I doing anything wrong in the configuration or is there some issue in the Okta package ?

**Comment by laura-rodriguez** [comment]
Hi Giorgi,

Can you please give more details of the use case you are trying to cover? If you use the Okta.AspNet SDK, it will configure an OIDC middleware for you which will redirect you to the Okta login when you try to log in.

Are you planning to show how to login with 2 different providers?

**Comment by Giorgi** [comment]
Hi Laura,

My use case is to use ASP.NET Identity for creating new users and saving them in Okta and using Okta to log in with Okta. As I said I'm redirected to Okta as expected but I get the error I posted above. But the same thing works with the `AspNet.Security.OAuth.Okta` package. The demo repo that I have has both packages installed so that you can try it easily.

**Comment by laura-rodriguez** [comment]
Hi @Giorgi ,

Thank you for the details.

We were able to reproduce the issue, but we'll need some time to investigate further. 

We have created an internal JIRA to work on this. We'll get back to you when we have updates.

Thanks!

**Comment by andriizhegurov-okta** [comment]
Fixed in Okta.AspNetCore v3.5.1
