### ISSUE TITLE
openid-configuration issue

### ISSUE THREAD

**Issue by cr1t** [okta/okta-aspnet#157]
Good day 

We are trying to integrate OKTA SSO for a client of ours that is using OKTA. 
We have used the Okta Middleware and we are using OpenID as a protocol
In there production environment there configuration file is located at https://{client}okta.com/.well-known/openid-configuration
in stead of https://{client}.okta.com/oauth2/default/.well-known/openid-configuration according to there Okta consultant it is due to them not having the oauth API (I'm a bit fuzzy on this details)

I've traced the code and in the project Okta.AspNet.Abstractions under the class uri helper

`
        public static string CreateIssuerUrl(string oktaDomain, string authorizationServerId)
        {
            if (string.IsNullOrEmpty(oktaDomain))
            {
                throw new ArgumentNullException(nameof(oktaDomain));
            }

            if (string.IsNullOrEmpty(authorizationServerId))
            {
                return oktaDomain;
            }

            return $"{EnsureTrailingSlash(oktaDomain)}oauth2/{authorizationServerId}";
        }
`

the domain is being concatenated with oauth2/default.

Short from forking the project and changing this I'm not sure what to do.

**Comment by bryanapellanes-okta** [comment]
@cr1t ,
Thanks for reaching out and I apologize for the inconvenience.  Is there an exception occurring?  To help me understand the broader context of the problem, are you able to provide code that reproduces the issue?

**Comment by cr1t** [comment]
Hi Bryan

The consultant came back and the solution is to set the AuthorizationServerId = "", 

`
public class Startup
{
    public void Configuration(IAppBuilder app)
    {
        // ...
        app.UseOktaMvc(new OktaMvcOptions()
        {
            OktaDomain = ConfigurationManager.AppSettings["okta:OktaDomain"],
            ClientId = ConfigurationManager.AppSettings["okta:ClientId"],
            ClientSecret = ConfigurationManager.AppSettings["okta:ClientSecret"],
            RedirectUri = ConfigurationManager.AppSettings["okta:RedirectUri"],
            AuthorizationServerId = "",
        });
    }
}
`
