### ISSUE TITLE
Expose NameClaimType in Okta.AspNet: OktaMvcOptions

### ISSUE THREAD

**Issue by ave-303** [okta/okta-aspnet#160]
We are making the change to Okta as our IdP within our organization.  I am working with some old solutions that rely heavily on User.Identity.Name to look up users within ASP.Membership.  The code bases also rely heavily on Roles.IsUserInRole.

The use of this seems to be tied to having the 'sub' claim set as the NameClaimType, rather than 'name'.  I have Okta providing user authentication, however, I get errors looking up the MembershipUser and Roles because the NameClaimType is hard coded to return 'name' in Asp.Net OpenIdConnectAuthentionOptionsBuilder.cs:

```
        /// <summary>
        /// Creates a new instance of OpenIdConnectAuthenticationOptions.
        /// </summary>
        /// <param name="oktaMvcOptions">The <see cref="OktaMvcOptions"/> options.</param>
        /// <returns>A new instance of OpenIdConnectAuthenticationOptions.</returns>
        public OpenIdConnectAuthenticationOptions BuildOpenIdConnectAuthenticationOptions()
        {
            var tokenValidationParameters = new DefaultTokenValidationParameters(_oktaMvcOptions, _issuer)
            {
                NameClaimType = "name",
                ValidAudience = _oktaMvcOptions.ClientId,
            };
```

I realize that these code bases really need updated...that's a big topic of discussion.  However, if NameClaimType were exposed in OktaMvcOptions (or perhaps the TokenValidationParameters) and the ability to set NameClaimType to 'sub' were an option, I can seamlessly integrate with Okta with hardly any code changes, and that would be HUGE for us as we have many applications that use this old paradigm.

I've google'd other options of setting the NameClaimType after the fact, but I haven't found anything; is there a known work around for this situation?

Here are the changes I'd expect to see:

Okta.AspNet OktaMvcOptions.cs
```
public class OktaMvcOptions : Abstractions.OktaWebOptions
{
   . . .

         /// <summary>
        /// Gets or sets NameClaimType returned to the User Identity
        /// </summary>
        /// <value>The Name Claim Type, default is "name"</value>
        public string NameClaimType { get; set; } = "name";

    . . .
}
```
in Okta.AspNet OpenIdConnectAuthenticationOptions.cs

  ```
        /// <summary>
        /// Creates a new instance of OpenIdConnectAuthenticationOptions.
        /// </summary>
        /// <param name="oktaMvcOptions">The <see cref="OktaMvcOptions"/> options.</param>
        /// <returns>A new instance of OpenIdConnectAuthenticationOptions.</returns>
        public OpenIdConnectAuthenticationOptions BuildOpenIdConnectAuthenticationOptions()
        {
            var tokenValidationParameters = new DefaultTokenValidationParameters(_oktaMvcOptions, _issuer)
            {
                NameClaimType = _oktaMvcOptions.NameClaimType,
                ValidAudience = _oktaMvcOptions.ClientId,
            };
```

Looking forward to hearing if this could be an option, thanks for your time!

**Comment by bryanapellanes-okta** [comment]
@ave-303,
Thanks for reaching out!  I'll add an item to our internal backlog for prioritization; meanwhile, if you're so inclined, feel free to submit a pull request with your proposed changes and we will review for inclusion in the next release.  The code you propose looks completely reasonable and sane to me.

**Comment by bryanapellanes-okta** [comment]
@ave-303,
As an alternative, you might consider using the `OnTokenValidated` event to execute your custom logic.  First define the method to execute:

```
private static async Task OnTokenValidatedAsync(TokenValidatedContext context)
        {
            ClaimsIdentity claimsIdentity = context.Principal.Identity as ClaimsIdentity;
            claimsIdentity.AddClaim(new Claim("CodeTokenCustomClaim", "CodeTokenCustomClaim"));
            return;
        }
```
then set the method when other configuration options are set
```
   .AddOktaMvc(new OktaMvcOptions
            {
                // Replace these values with your Okta configuration
                OktaDomain = Configuration.GetValue<string>("Okta:OktaDomain"),
                ClientId = Configuration.GetValue<string>("Okta:ClientId"),
                ClientSecret = Configuration.GetValue<string>("Okta:ClientSecret"),
                OnTokenValidated = OnTokenValidatedAsync,
            });
```
Let me know if this works.  Thanks!

**Comment by ave-303** [comment]
Do you mean "SecurityTokenValidated"?  I don't have a "OnTokenValidated" even to sign up for.  Nor do I have a TokenValidatedContext.

None the less, I have access to the 'sub' claim, it's that it's not assigned to User.Identity.Name...does the code you provided assign it to User.Identity.Name?

Thanks!

**Comment by ConnorJBishop** [comment]
I have a similar need but for `RoleClaimType` instead, I think if this change will be made then it should include both.

I have however found a workaround using the `OnTokenValidated` event as @bryanapellanes-okta mentioned. To customize the name/role claim type you can do this:
```csharp
private static Task OnTokenValidated(TokenValidatedContext context)
{
    // Define custom claim types
    string customNameClaimType = "sub";
    string customRoleClaimType = "custom_role";

    var currentIdentity = context.Principal.Identity;
    // Create new customized ClaimsIdentity with claim types defined above
    var customIdentity = new ClaimsIdentity(
        currentIdentity, new List<Claim>(), currentIdentity.AuthenticationType, customNameClaimType, customRoleClaimType
    );
    // Overwrite the context.Principal with a new instance which will be identical apart from the
    // name and role claim types
    context.Principal = new ClaimsPrincipal(customIdentity);
    return Task.CompletedTask;
}

.AddOktaMvc(new OktaMvcOptions
{
    // Replace these values with your Okta configuration
    OktaDomain = Configuration.GetValue<string>("Okta:OktaDomain"),
    ClientId = Configuration.GetValue<string>("Okta:ClientId"),
    ClientSecret = Configuration.GetValue<string>("Okta:ClientSecret"),
    OnTokenValidated = OnTokenValidated,
});
```

**Comment by bryanapellanes-okta** [comment]
@ConnorJBishop 
Thank you for your input!  The code you've posted should address @ave-303's needs.  

@ave-303 Please also see a similar approach here: https://github.com/okta/samples-aspnetcore/compare/OKTA-361933-oktaidentity?expand=1

**Comment by ave-303** [comment]
This looks fantastic!  

I just have one problem...  I am using the Okta.AspNet package...not Okta.AspNetCore package, and it looks to me that the OktaMvcOptions vary slightly between the two packages.  Namely, I don't have the OnTokenValidated event to add.  Is this equivalent to SecurityTokenValidated?

The function signatures vary slightly as well...

Okta.AspNet OktaMvcOptions:
```
public Func<SecurityTokenValidatedNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions>, Task> SecurityTokenValidated { get; set; } = notification => Task.FromResult(0)
```
Okta.AspNetore OktaMvcOptions:
```
public Func<TokenValidatedContext, Task> OnTokenValidated { get; set; } = context => Task.CompletedTask;
```

Assuming they serve the same purpose, I've taken a stab at implementing the function for Okta.AspNet:
```

app.UseOktaMvc(new OktaMvcOptions()
    {
        OktaDomain = ConfigurationManager.AppSettings("okta:OktaDomain"),
        ClientId = ConfigurationManager.AppSettings("okta:ClientId"),
        ClientSecret = ConfigurationManager.AppSettings("okta:ClientSecret"),
        RedirectUri = ConfigurationManager.AppSettings("okta:RedirectUri"),
        PostLogoutRedirectUri = ConfigurationManager.AppSettings("okta:PostLogoutRedirectUri"),
        GetClaimsFromUserInfoEndpoint = true,
        Scope = new List<string>(
        {
            "openid",
            "profile",
            "email"
        }),
        AuthenticationFailed = OnAuthenticationFailed,        
        SecurityTokenValidated = OnTokenValidated
    });


private Task OnTokenValidated(SecurityTokenValidatedNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> context)
{
    string customNameClaimType = "sub";
    string customRoleClaimType = "custom_role";
    var currentIdentity = context.AuthenticationTicket.Identity as ClaimsIdentity;
    var customIdentity = new ClaimsIdentity(currentIdentity, new List<Claim>(), currentIdentity.AuthenticationType, customNameClaimType, customRoleClaimType);

    // Overwrite the context.Principal with a new instance which will be identical apart from the
    // name And role claim types
    var principal = new ClaimsPrincipal(customIdentity);
    var identity = principal.Identity as ClaimsIdentity;

    var properties = context.AuthenticationTicket.Properties;

    var ticket = new AuthenticationTicket(identity, properties);
    context.AuthenticationTicket = ticket;

    return Task.CompletedTask;
}

```

It seems to work...and I'm sure what I have is total overkill, but I'll take it.  

Thanks so much!

**Comment by bryanapellanes-okta** [comment]
@ave-303,
I'm glad you have a working solution.  Feel free to follow up with any other questions.

Thanks for using Okta!

**Comment by ConnorJBishop** [comment]
Thought Id just add a quick update here. For .NET Core its even easier than I first imagined. You can simply do the following:

```csharp
services.PostConfigureAll<OpenIdConnectOptions>(opt =>
{
    opt.TokenValidationParameters.NameClaimType = "bar";
    opt.TokenValidationParameters.RoleClaimType = "bar";
});
```

I knew Microsoft created the options pattern for a reason. Just make sure this placed after the `AddOktaMvc` call.

**Comment by ave-303** [comment]
@ConnorJBishop, 

Any idea if this as available in ASP.Net?  I have access to the IAppBuilder in the Configuration method of Startup.cs.
