### ISSUE TITLE
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.

### ISSUE THREAD

**Issue by KeithBarrows** [okta/okta-aspnet#161]
We have an Angular UI that calls a C# based Core 3.x API.  The Angular app works perfectly and I have access to everything I need from Okta.

When passing the Bearer token to the API we either get a 401 Forbidden or the following error:

> System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
 ---> System.IO.IOException: IDX20807: Unable to retrieve document from: 'System.String'. HttpResponseMessage: 'System.Net.Http.HttpResponseMessage', HttpResponseMessage.Content: 'System.String'.
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
> 
> HEADERS
> =======
> Accept: */*
> Accept-Encoding: gzip, deflate, br
> Authorization: Bearer > eyJraWQiOiIwVVl5RlJVQjVS*******************
> Cache-Control: no-cache
> Connection: keep-alive
> Host: 5cg9061psw.corp.ryder.com:8863
> User-Agent: PostmanRuntime/7.26.8
> Postman-Token: 7d4a63a1-93b9-4864-9da5-531a355895d4

I have even tried this against my dev instance of Okta to rule out needing an Authority Server.  I get the same results.

C# Startup:
-------------------
```
using MediatR;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Okta.AspNetCore;
using Ryder.FDM.Api.Services.Behaviors;
using Ryder.FDM.Api.Services.Caching;
using Ryder.FDM.Api.Services.CommandHandlers;
using Ryder.FDM.Data.Unify;
using Ryder.FDM.Infrastructure.Extensions;
using Serilog;
using System;
using System.Net.Http;
using System.Reflection;
using System.Security.Principal;

......
public void ConfigureServices(IServiceCollection services)
{
.....
    services.AddAuthentication(options =>
    {
        options.DefaultAuthenticateScheme = OktaDefaults.ApiAuthenticationScheme;
        options.DefaultChallengeScheme = OktaDefaults.ApiAuthenticationScheme;
        options.DefaultSignInScheme = OktaDefaults.ApiAuthenticationScheme;
    })
    .AddOktaWebApi(new OktaWebApiOptions()
    {
        OktaDomain = $"{DataUnifyConfig.Instance.Authority}/oauth2/default",
    });
.....
}
```

I am copying the bearer token from the UI and using it in a Postman call to the API.  Is that effecting the results?

I have now spent 2 days trying to decipher the error message, trying every hack I can find on the Okta Dev Forums, GitHub, StackOverflow and noting is working.

**Comment by laura-rodriguez** [comment]
Hi @KeithBarrows ,

Thanks for reaching out. 

It seems your Web API configuration is not correct. In your `OktaDomain` you have to set your Org URL (something like this: `https://dev.okta.com`) instead of the issuer.  The SDK will create the issuer URI for you.

I hope this helps.

**Comment by KeithBarrows** [comment]
Hi @laura-rodriguez - I changed the startup to:
```
services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = OktaDefaults.ApiAuthenticationScheme;
    options.DefaultChallengeScheme = OktaDefaults.ApiAuthenticationScheme;
    options.DefaultSignInScheme = OktaDefaults.ApiAuthenticationScheme;
})
.AddOktaWebApi(new OktaWebApiOptions()
{
    OktaDomain = DataUnifyConfig.Instance.Authority,
});
```

In my appsettings I have:
```
"Authority": "https://dev-712283.okta.com",
```


This is now the result:
> Request URL: http://5cg9061psw.corp.ryder.com:8863/api/home?
> Request Method: GET
> Status Code: 401 Unauthorized
> Remote Address: 10.92.25.111:8863
> Referrer Policy: strict-origin-when-cross-origin
> Access-Control-Allow-Origin: *
> Content-Length: 0
> Date: Tue, 26 Jan 2021 18:31:35 GMT
> Server: Microsoft-HTTPAPI/2.0
> WWW-Authenticate: **Bearer error="invalid_token", error_description="The signature key was not found"**
> Accept: application/json, text/plain, */*
> Accept-Encoding: gzip, deflate
> Accept-Language: en-US,en;q=0.9
> Authorization: Bearer > eyJraWQiOiIwVVl5RlJVQjVS***************
> Connection: keep-alive
> Host: 5cg9061psw.corp.ryder.com:8863
> Origin: http://localhost:4200
> Referer: http://localhost:4200/
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36 Edg/88.0.705.50

Where do I find, where do I supply, the **signature key**?

**Comment by laura-rodriguez** [comment]
@KeithBarrows, your `OktaDomain` looks correct now. Can you double-check that you're using the same Authorization Server in both applications (Angular and Web API)? 

If you're using the `default` authorization server, the Web API project will hit https://dev-712283.okta.com/oauth2/default/.well-known/openid-configuration to get the public keys to verify the token signature. Can you verify that this request is being made and it's successful? It'd be great if you can share a Fiddler log.

**Comment by KeithBarrows** [comment]
Angular:
```
const oktaRedirectUri = 'http://localhost:4200/';
const oktaLoginRedirect = 'implicit/callback'; 
const oktaIssuer =  'https://dev-712283.okta.com';
const oktaClientId = '********************';

const config = {
  clientId: oktaClientId,
  issuer: oktaIssuer,
  redirectUri: oktaRedirectUri + oktaLoginRedirect,
  scopes: ['openid', 'profile', 'email'],
  pkce: true
};
```

Is this what you mean by the fiddler log?  (Sessions saved as SAZ format)

[FDM Okta 01.zip](https://github.com/okta/okta-aspnet/files/5875532/FDM.Okta.01.zip)

**Comment by KeithBarrows** [comment]
Opened up a few of the messages.  This might help??
![image](https://user-images.githubusercontent.com/3630422/105893854-99599f80-5fe1-11eb-9f38-ef14943e064f.png)

**Comment by laura-rodriguez** [comment]
Thanks for sharing! I think the issue is in your Angular configuration. In Angular, you have to set the issuer instead of the OktaDomain. I know this might cause confusion, but Angular doesn't build the issuer URI for you.

So, in Angular your issuer configuration should be `https://{yourOktaDomain}.com/oauth2/default` (`default` is your Authz server), so update the following line: `const oktaIssuer =  'https://dev-712283.okta.com/oauth2/default';`. 

The ASP.NET SDK uses the `default` Authorization Server by default, so if you don't change the `AuthorizationServerId` you should be fine.

This way both of your apps will use the same Authorization Server, so you should be able to validate the token since the keys should match now.

Let me know if this solves the issue.

**Comment by KeithBarrows** [comment]
Fixed!

Angular:  issuer string is explicit --> https://{yourDomain}/outh2/default
.NET: issuer string is implicit -->https://{yourDomain}

The string for issuer is passed in the token and compared each step of the way IIRC.  Since Angular only had the domain, not the full URL, .NET would never match up nor could it find the `well-known` endpoint.  Simple fix in the end - **once** you know what it is.  :D 

Thank you!!

**Comment by briandonahue** [comment]
> Fixed!
> 
> Angular: issuer string is explicit --> https://{yourDomain}/outh2/default
> .NET: issuer string is implicit -->https://{yourDomain}

You saved me after hours of spinning my wheels. My issue was actually the opposite - examples showed using the root domain, but for my auth provider (OneLogin) I had to have the OIDC endpoint `/oidc/2` at the end.
