### ISSUE TITLE
A suite of ASP.Net MVC & ASP.Net Webforms works internal but not with Okta Dashboard

### ISSUE THREAD

**Issue by mrtariqmahmood** [okta/okta-aspnet#163]
We have a suite of web applications based on ASP.Net MVC,ASP.NET Webform ranging from framework 4.6 to 4.8 together with .Net Core 2.1. They all work fine internally once logged on can browse all sites without login prompt.

 From our site we can logon to Okta Dashborad without prompt.

As we are testing sso & like to visit other Okta based sites within our organization having within same Federation. But if we sign to Okta Dashboard and then to our site it always prompts to sign on again.

We like to visit all sites within our Federation without being asked to logon again.

The code we wrote is from sample Okta ASP.NET mvc & webforms & core.

public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            // For more information on how to configure your application, visit http://go.microsoft.com/fwlink/?LinkID=316888

            SetCookieAuthenticationAsDefault(app);
        
            AddOktaAuthenticationMiddleware(app);
        }

        private void SetCookieAuthenticationAsDefault(IAppBuilder app)
        {
            System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Ssl3
                    | System.Net.SecurityProtocolType.Tls
                    | System.Net.SecurityProtocolType.Tls11
                    | System.Net.SecurityProtocolType.Tls12;

            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
            app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                //AuthenticationMode = AuthenticationMode.Active,
                //AuthenticationType = "Cookies",
                //CookieManager = new SystemWebCookieManager(),   
                ExpireTimeSpan = System.TimeSpan.FromMinutes(60),
                SlidingExpiration = true,
                LoginPath = new PathString("/Account/Login")
            });
            app.UseKentorOwinCookieSaver();
        }

        private void AddOktaAuthenticationMiddleware(IAppBuilder app)
        {            
            app.UseOktaMvc(new OktaMvcOptions()
            {
                OktaDomain = ConfigurationManager.AppSettings["okta:OktaDomain"],
                ClientId = ConfigurationManager.AppSettings["okta:ClientId"],
                ClientSecret = ConfigurationManager.AppSettings["okta:ClientSecret"],
                RedirectUri = ConfigurationManager.AppSettings["okta:RedirectUri"],
                PostLogoutRedirectUri = ConfigurationManager.AppSettings["okta:PostLogoutRedirectUri"],
                GetClaimsFromUserInfoEndpoint = true,
                Scope = new List<string> { "openid", "profile", "email" },
                LoginMode = LoginMode.SelfHosted,
            });
        }
    }
}

We use Okta login widget embeded in our login page.

  [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(FormCollection form)
        {
            if (HttpContext.User.Identity.IsAuthenticated) return RedirectToAction("Index", "Home");

            string query = Request.QueryString["ReturnUrl"];
            var properties = new AuthenticationProperties();
            properties.Dictionary.Add("sessionToken", form.Get("sessionToken"));
            string ReturnUrl = form.Get("ReturnUrl");
            string reset = string.IsNullOrWhiteSpace(Request.Form["PasswordReset"]) ? "off" : Request.Form["PasswordReset"].ToString();
            if (!string.IsNullOrWhiteSpace(ReturnUrl))
            {
                properties.RedirectUri = ReturnUrl;
            }
            else if (!string.IsNullOrWhiteSpace(query))
            {
                properties.RedirectUri = query;
            }
            else
            {
                properties.RedirectUri = "/home/index";
            }
            if (reset == "on")
            {
                properties.RedirectUri = "/account/changepassword";
            }
            // Challenge Auth
            HttpContext.GetOwinContext().Authentication.Challenge(properties, OktaDefaults.MvcAuthenticationType);
            // Return
            return new HttpUnauthorizedResult();
        } 

We are about to go live & our company expect once logged in should be able visit other company sites without any further login prompt.

## Environment

- OS: Windows 10 - windows server
- .Net Framework: 
.Net 4.8 framework & .Net ASP webform & .Net Core 2.1

**Comment by bryanapellanes-okta** [comment]
@mrtariqmahmood,
Thanks for reaching out!  The scenario you describe is not supported out of the box.  Reach out to our support team at developers@okta.com, and they can hear the details of your use-case and discuss which options would best meet your needs.

Thanks for using Okta!
