### ISSUE TITLE
Compatibility problem with antiforgery provider

### ISSUE THREAD

**Issue by SeminDM** [okta/okta-aspnet#165]
Hello!
In the class `OpenIdConnectAuthenticationOptionsBuilder` I noticed the [method](https://github.com/okta/okta-aspnet/blob/187f33eba4079bc2bbad070a61e5d99c5d9c9e94/Okta.AspNet/OpenIdConnectAuthenticationOptionsBuilder.cs#L137) which ensures claim `NameIdentifier` has a value. But default mvc antiforgery protector throws exception

    A claim of type 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier' or 'http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider' was not present on the provided ClaimsIdentity.
    
I expose claims of current `ClaimsIdentity` object and this claim is present in claim's collection!

    // {http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier: 00u4ayuydpB5h6gCW5d6}
    var owinUser = HttpContext.Current.GetOwinContext().Authentication.User;
    var user = HttpContext.Current.User.Identity;
    @Html.AntiForgeryToken()

Why does protector throw this exception?
I don't want change `AntiForgeryConfig.UniqueClaimTypeIdentifier` on other property beacouse other idps (for instance, Azure AD) fill this claim type.

Thanks!

**Comment by bryanapellanes-okta** [comment]
@SeminDM,
Thanks for reaching out!  To help me diagnose the issue, I have some questions:

- Can you share code that reproduces the issue?
- Can you direct me to the point in the code where the exception is thrown? (link provided in comment returns no results)

**Comment by SeminDM** [comment]
@bryanapellanes-okta sorry for empty link, I fixed it.
I solved problem just now. I added `email` scope and exception is gone but I don't understand why?

`Startup.cs`

    app.SetDefaultSignInAsAuthenticationType(AuthTypes.Cookies);
    app.UseCookieAuthentication(new CookieAuthenticationOptions());

    app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
    {
        AuthenticationType = AuthTypes.AzureAD,
        ClientId = azureConnector.ClientId,
        Authority = azureConnector.Authority,
        RedirectUri = azureConnector.RedirectUri,
        PostLogoutRedirectUri = azureConnector.PostLogoutRedirectUri,
        Scope = OpenIdConnectScope.OpenIdProfile,
        ResponseType = OpenIdConnectResponseType.IdToken,
        TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = false
        }
    });

    app.UseOktaMvc(new OktaMvcOptions
    {
        OktaDomain = oktaConnector.Authority,
        ClientId = oktaConnector.ClientId,
        ClientSecret = oktaConnector.ClientSecret,
        RedirectUri = oktaConnector.RedirectUri,
        PostLogoutRedirectUri = oktaConnector.PostLogoutRedirectUri,
        Scope = new List<string> { "openid", "profile", "email" /*this scope solved problem!*/ },
        LoginMode = LoginMode.SelfHosted
    });
    
 `HomeController`

    public void LoginByOkta()
    {
        if (!Request.IsAuthenticated)
        {
            HttpContext.GetOwinContext().Authentication.Challenge(AuthTypes.Okta);
        }
        else
        {
            ClaimsIdentity claimsIdentity = User.Identity as ClaimsIdentity;
            AuthenticationModule.LoginByClaims(claimsIdentity);
        }
    }
    
`Login.cshtml`    

    @using (Html.BeginForm())
    {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

          <a href="@Url.Action("LoginByOkta", "Home", null)" style="text-decoration: none;">
    }

**Comment by bryanapellanes-okta** [comment]
@SeminDM,
I'm glad you were able to find a solution!  I believe the email scope is required for the "sub" scope to be included.

Thanks for using Okta!
