### ISSUE TITLE
Okta.AspNet is not strongly-named assembly

### ISSUE THREAD

**Issue by SeminDM** [okta/okta-aspnet#166]
Hello!
I have exception

`System.IO.FileLoadException: Could not load file or assembly 'Okta.AspNet, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required `

Why this library (and Okta.AspNet.Abstractions) is not strongly-named?
How to solve this problem?

**Comment by andriizhegurov-okta** [comment]
Hi @SeminDM,
I guess you're referencing `Okta.AspNet` which is not currently being signed from a signed assembly. Am I correct? I will add an item to our backlog to address that case. 
Meanwhile you may use [strongnamer package](https://github.com/dsplaisted/strongnamer) which solves the problem by signing what is needed.

**Comment by SeminDM** [comment]
Yes, you are correct. Strongenamer breaks my app: there are several different errors with assemblies at the apllication start.

**Comment by andriizhegurov-okta** [comment]
@SeminDM here is another strong name signer, you may give it a try [https://brutaldev.com/post/NET-Assembly-Strong-Name-Signer](https://brutaldev.com/post/NET-Assembly-Strong-Name-Signer)

**Comment by SeminDM** [comment]
All the same. I have to refuse Okta.AspNet for the while.
Thanks for reply!

**Comment by plqplq** [comment]
This is still an issue, I would suggest that having this security flaw present, given okta's position in the market place, is at best an embarrasment and at worst a serious vulnerability since a hacker could gain access to a customer server and replace OKTA's DLLs with their own

**Comment by bryanapellanes-okta** [comment]
@plqplq,
Thanks for your input!  We've elevated the priority of this work.

**Comment by bkadhim** [comment]
I just ran into this issue myself and was shocked to find that this thread has been open since February. Is this likely to get fixed any time soon?

**Comment by andriizhegurov-okta** [comment]
The latest packages are strong named:
* Asp.Net v1.8.2
* Asp.Net.Abstraction v3.2.2

**Comment by laura-rodriguez** [comment]
Fixed in v1.8.2
