### ISSUE TITLE
Why does Okta require to enter user credentials for sign-in after sign-out?

### ISSUE THREAD

**Issue by SeminDM** [okta/okta-aspnet#169]
Hello!
I want to understand SSO concept.
1. I signed into https://dev-...-admin.okta.com/
2. I open Loginpage of my app and press button "Login by Okta"
3. I am signed into my app **automatically** (Okta doesn't require to enter my credentials)
4. I do **log out** from my app.
5. I open Loginpage of my app and press button "Login by Okta" again.
6. Okta **requires to enter** my credentials

Why Okta requires my credentials after logout?
What is changed before second login attempt comparing before first login attempt?

I work on Asp.net Framework and use OWIN and OpenId Connect.

I found out that Azure AD use [Primary Refresh Token](https://docs.microsoft.com/en-us/azure/active-directory/devices/concept-primary-refresh-token) for SSO and when I explicitly signs out of the app, the PRT cookie and Session cookies are explicitly marked as expired and are invalidated.

Does Okta use PRT?

**Comment by andriizhegurov-okta** [comment]
Hi @SeminDM,
In both cases whether you logged in from your App or logged into your organization's admin console, you are being authenticated by your Org Authorization Server. When you are logged out of your session from admin console, your App will again ask you for your credentials.

You can check our blog for information on SSO, for example in this article https://www.okta.com/blog/2021/02/single-sign-on-sso/

**Comment by SeminDM** [comment]
I understand that if I do log out from admin console I will be log out from my app. But I don't understand why first time Okta authenticate me automatically in my app, but after **sign-out from my app** Okta requires to reenter my credentials to sign-in in the app. I don't log out from admin console at all.

**Comment by andriizhegurov-okta** [comment]
@SeminDM I think your Okta session was still active at the time you ran your App.

So, you have 2 diff ways of approaching log out:

1. You can log out from your app (this basically "kills" your app cookie, but your okta session remains so next time you login and there's still an okta session cookie you won't have to enter your credentials: https://developer.okta.com/docs/guides/sign-users-out/aspnet/sign-out-of-your-app/)

2. You can log out from okta (this kills the okta session cookie so next time you login you will have to provide your creds: https://developer.okta.com/docs/guides/sign-users-out/aspnet/sign-out-of-okta/)

**Comment by SeminDM** [comment]
@andriizhegurov-okta ok. thank you!
