### ISSUE TITLE
AddOktaMvc does not use a non-default Authentication Server when AuthenticationServerId is provided

### ISSUE THREAD

**Issue by tylerlemieux** [okta/okta-aspnet#174]
## Current behavior

AuthenticationServerId is specified in OktaMvcOptions and AddOktaMvc is called in startup, but api://default is still being used as the authentication server.

In the Okta.AspNetCore package it looks like in the middleware code the AddOktaWebApi() calls the AddJwtValidation() and the Authentication Server URL gets set, but in the middleware code for AddOktaMvc() AddJwtValidation() does not get called so api://default is used.

## Expected behavior

When AuthenticationServerId is specified in the OktaMvcOptions it should be used as the Authentication Server instead of default.

## Minimal reproduction of the problem with instructions

Using dotnet 5 create a MVC application and use the following code in Startup.cs.  I replaced the actual settings I am using to not reveal any secrets

```C#
var oktaMvcOptions = new OktaMvcOptions()
{
    OktaDomain = "<domain>",
    ClientId = "<clientId>",
    ClientSecret = "<clientSecret>",
    Scope = new List<string> { "openid", "profile", "email",  },
    AuthorizationServerId = "<AuthenticationServerId>",                
};

services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = OktaDefaults.MvcAuthenticationScheme;
})
.AddCookie()
.AddOktaMvc(oktaMvcOptions);
```

## Environment

- OS: OSX
- Browser: Tested with Chrome and Edge

- .Net Framework: ASPNET 5

- Other:

**Comment by andriizhegurov-okta** [comment]
Thank you for reporting the issue, I've added it to our backlog for prioritization. 
We'll follow up here.

**Comment by tylerlemieux** [comment]
Over the weekend something that was being cached must have cleared out and the claims started being populated.  I will close the issue, thank you.
