### ISSUE TITLE
Add ability to set custom authentication scheme on JwtBearer

### ISSUE THREAD

**Issue by Kilowhisky** [okta/okta-aspnet#175]
## User story
As a API provider i want to accept multiple types of JWT Tokens so that i can serve both internal users and external users. 

Assume an API handles an admin portal and a client side portal. The admin side portal authenticates with a proprietary JWT and the client side authenticates with Okta. It is currently not possible to support both authentication mechanism as .NET Core 3.1+ requires multiple registered JWT Providers be identified with a different `authenticationScheme`

## Proposed solution

Add in to the `OktaWebApiOptions` a property for `AuthenticationScheme` and then pass that property to the method `AddJwtBearer()` located here. 

https://github.com/okta/okta-aspnet/blob/b15676a5033bbfd4eb92e593fe9d2f579b07f3b6/Okta.AspNetCore/OktaAuthenticationOptionsExtensions.cs#L90-L111

## Alternatives considered
There is no other alternatives available. .NET will explode if you try to add multiple `JwtBearers()` without it. 

## Additional information
See this for information on why this is necessary. 
https://stackoverflow.com/questions/49694383/use-multiple-jwt-bearer-authentication

**Comment by andriizhegurov-okta** [comment]
@Kilowhisky thank you for the suggestion. I've added an internal item to review it and take needed actions.

**Comment by laura-rodriguez** [comment]
Fixed in [Okta.AspNet 3.0.0](https://www.nuget.org/packages/Okta.AspNet/3.0.0) and [Okta.AspNetCore 4.2.0](https://www.nuget.org/packages/Okta.AspNetCore/4.2.0).
