### ISSUE TITLE
Unable to set all events in OpenIdConnectEvents class.

### ISSUE THREAD

**Issue by nivanov-stitan** [okta/okta-aspnet#177]
We need to setup events for all OpenIdConnectEvents for our needs. 
Currently this library allow only 4 events declared in https://github.com/okta/okta-aspnet/blob/master/Okta.AspNetCore/OktaMvcOptions.cs :
- OnTokenValidated
- OnUserInformationReceived
- OnOktaApiFailure
- OnAuthenticationFailed

The part of our issues will resolve this PR https://github.com/okta/okta-aspnet/pull/110 but it's not merged yet.

**Comment by andriizhegurov-okta** [comment]
Hi @nivanov-stitan. Thanks for the request. 
I'll add an item to our backlog for this. We'll keep you updated here.

**Comment by nivanov-stitan** [comment]
Thanks

**Comment by laura-rodriguez** [comment]
OIDC and JWT events are now exposed. This feature is available in Okta.AspNet 2.0.0 and Okta.AspNetCore 4.0.0. Fixed in #187.
