### ISSUE TITLE
Signature validation failed. when running the .net core 5 application in server but works fine locally

### ISSUE THREAD

**Issue by m-garlapati** [okta/okta-aspnet#179]
I have a .net core blazor project when I run the application locally it works with http://localhost:5001. But when I publish and deploy the application to IIS on the server I am getting below error.

ERROR Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler [(null)] - Exception occurred while processing message.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10511: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.RsaSecurityKey, KeyId: 'SGxE03ChiJPuLv6JDFSCBJ07qbeSAzKZ1E_Q3gJpRSY', InternalId: 'BwQzL_xHEMI8SIpVsoQwZ5Bh3Utee8a6SJU1MlW7fTM'. , KeyId: SGxE03ChiJPuLv6JDFSCBJ07qbeSAzKZ1E_Q3gJpRSY
'. 
kid: 'SGxE03ChiJPuLv6JDFSCBJ07qbeSAzKZ1E_Q3gJpRSY'. 
Exceptions caught:
 'System.TypeInitializationException: The type initializer for 'System.Security.Cryptography.CngKeyLite' threw an exception.
 ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: An internal error occurred.
   at System.Security.Cryptography.CngKeyLite.OpenNCryptProvider(String providerName)
   at System.Security.Cryptography.CngKeyLite..cctor()
   --- End of inner exception stack trace ---
   at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, ReadOnlySpan`1 keyBlob, Boolean encrypted, ReadOnlySpan`1 password)
   at System.Security.Cryptography.RSAImplementation.RSACng.ImportKeyBlob(Byte[] rsaBlob, Boolean includePrivate)
   at System.Security.Cryptography.RSAImplementation.RSACng.ImportParameters(RSAParameters parameters)
   at Microsoft.IdentityModel.Tokens.AsymmetricAdapter.InitializeUsingRsaSecurityKey(RsaSecurityKey rsaSecurityKey, String algorithm)
   at Microsoft.IdentityModel.Tokens.AsymmetricAdapter..ctor(SecurityKey key, String algorithm, HashAlgorithm hashAlgorithm, Boolean requirePrivateKey)
   at Microsoft.IdentityModel.Tokens.AsymmetricAdapter..ctor(SecurityKey key, String algorithm, HashAlgorithm hashAlgorithm, HashAlgorithmName hashAlgorithmName, Boolean requirePrivateKey)
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.ResolveAsymmetricAdapter(SecurityKey key, String algorithm, Boolean requirePrivateKey)
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(SecurityKey key, String algorithm, Boolean willCreateSignatures, CryptoProviderFactory cryptoProviderFactory)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateSignatureProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures, Boolean cacheProvider)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForVerifying(SecurityKey key, String algorithm, Boolean cacheProvider)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForVerifying(SecurityKey key, String algorithm)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
'.
token: '{"kid":"SGxE03ChiJPuLv6JDFSCBJ07qbeSAzKZ1E_Q3gJpRSY","alg":"RS256"}.{"sub":"00us2ygyoUaQwlV3z5d6","name":"test","ver":1,"iss":"https://dev-63489489.okta.com/oauth2/aus1mvfryxlWjyFIY5d7","aud":"0oa1mkusnyiGkCooA5d7","iat":1630708985,"exp":1630712585,"jti":"ID.rngzABMzBtxEPOWxqWxbmnzfOVMT2716hMG90Az2v_A","amr":["pwd"],"idp":"00os2ygt0svhWwQ3P5d6","nonce":"637663057829869169.ZDUxZGRjYmEtM2E5OS00NzgwLWFjNjItYzdhYzYwMWY1MzM3Y2RhNDhkNzEtOWUzNC00YzI5LWJlZTUtYzRjYWNmOTMwM2Rl","preferred_username":"test@test.com","auth_time":1630708333,"at_hash":"eRU_tSyQQAUvujRMCPtIbg"}'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ValidateToken(String idToken, AuthenticationProperties properties, TokenValidationParameters validationParameters, JwtSecurityToken& jwt)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()

**Comment by bryanapellanes-okta** [comment]
@m-garlapati,
Thanks for reaching out!  It appears that the underlying Microsoft OIDC library is failing to validate the signature of the bearer token.  Additional information on the topic can be found here: https://developer.okta.com/docs/guides/validate-access-tokens/dotnet/overview/#what-to-check-when-validating-an-access-token

To help us troubleshoot further please provide code that reproduces the behavior and steps to reproduce and we'll investigate further.

Thanks for using Okta!

**Comment by m-garlapati** [comment]
Hi Bryan, I used the exact same code from this document https://developer.okta.com/blog/2019/10/16/csharp-blazor-authentication.

And on okta admin page I created custom authorization same as default auth server and I tried with both the servers but still the same issue, when I publish and deploy it remote server and configured in IIS.

From my local machine when I run the project from visual studio it works fine.

The only difference between the local machine and server is IIS. I though it is worth mentioning.


Thanks,

Mounika Garlapati
.net Developer
    p: 312-379-2397
     f: 312-379-2397
***@***.******@***.***>
www.fidelitylife.com<http://www.fidelitylife.com>
***@***.***

**Comment by bryanapellanes-okta** [comment]
@m-garlapati,
Thanks for the additional information!  I've entered an internal ticket for further investigation, we'll comment here when we have more.

**Comment by m-garlapati** [comment]
Sounds good. Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by m-garlapati** [comment]
Hi Bryan, I am able to reproduce the error on my local machine. When I run the application in IIS I am getting same error message.


Thanks,

Mounika Garlapati
.net Developer
    p: 312-379-2397
     f: 312-379-2397
***@***.******@***.***>
www.fidelitylife.com<http://www.fidelitylife.com>
***@***.***

**Comment by m-garlapati** [comment]
Hi Bryan, any update on the issue?

Thanks,

Mounika Garlapati
.net Developer
    p: 312-379-2397
     f: 312-379-2397
***@***.******@***.***>
www.fidelitylife.com<http://www.fidelitylife.com>
***@***.***

**Comment by bryanapellanes-okta** [comment]
@m-garlapati,
Thanks for your patience!  This work needs to be prioritized against other work in flight; we do expect to begin this investigation soon.  We'll update here when we have a better understanding of the issue.

Thanks for using Okta!

**Comment by m-garlapati** [comment]
Ok. Thank for the update

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bryanapellanes-okta** [comment]
@m-garlapati,
I'm working through publishing the test app to a local IIS instance.  To help me to reproduce the issue you are seeing, please provide the steps you used to publish to IIS.

**Comment by m-garlapati** [comment]
Steps to publish app to IIS

  1.  Build the application
  2.  Publish the application to any folder
  3.  Create and new website and IIS app pool
  4.  From IIS website set the path to your published folder
  5.  Setup https binding and run the application

Please let me know if you have any questions.

Thanks,

Mounika Garlapati
.net Developer
    p: 312-379-2397
     f: 312-379-2397
***@***.******@***.***>
www.fidelitylife.com<http://www.fidelitylife.com>
***@***.***

**Comment by bryanapellanes-okta** [comment]
@m-garlapati,
After [installing the necessary components (IIS, dotnet-hosting, etc.) and] following the steps you described, I'm not able to reproduce the behavior as described.  

A couple things to double check:
- make sure the `issuer` is set correctly in your appsettings.json, note that the path **/oauth2/default** is appended. 
 See https://d33wubrfki0l68.cloudfront.net/e067301e8e8b93b0f544216b542cccb2d8c7b094/b9a51/assets-jekyll/blog/csharp-blazor-authentication/json-settings-ac146fa9328e5a8539fcfc139e357c7cd4bae7f04d4b7cfdc6771c0e60fd4f08.png
- for my system I had to make sure that there is a Sign-in redirect URI registered in the Okta admin dashboard using `https`.
![Login-screenshot](https://user-images.githubusercontent.com/63638027/133259850-6785d96f-803a-4556-96ae-e7c2e93df439.png)


Are you using a custom domain?

**Comment by m-garlapati** [comment]
Hi Bryan, I have set issuer to https://dev-63489489.okta.com/oauth2/aus1mvfryxlWjyFIY5d7 and added in sign in redirect uri, and yes I am using custom domain.

***@***.***

Mounika Garlapati
.net Developer
    p: 312-379-2397
     f: 312-379-2397
***@***.******@***.***>
www.fidelitylife.com<http://www.fidelitylife.com>
***@***.***

**Comment by bryanapellanes-okta** [comment]
@m-garlapati,
On the surface this appears to be related to the custom domain.  Please email support@okta.com to open a support ticket and they will work with you directly to troubleshoot the issue further.

**Comment by m-garlapati** [comment]
I already did that and they redirected me to you. They couldn’t figure out the issue.

Can you please explain ”On the surface this appears to be related to the custom domain”?

Thanks,

Mounika Garlapati
.net Developer
    p: 312-379-2397
     f: 312-379-2397
***@***.******@***.***>
www.fidelitylife.com<http://www.fidelitylife.com>
***@***.***

**Comment by bryanapellanes-okta** [comment]
> Can you please explain ”On the surface this appears to be related to the custom domain”?

Failure to validate the signature is generally caused by misalignment somewhere between the issuer, custom domain/url and authorization servers.

**Comment by m-garlapati** [comment]
Previously I had a call with support and showed the issue they were not able to help me and then asked to create the issue https://github.com/okta/okta-aspnet/issues. I am actually going back and forth on this issue. Not sure how can I resolve this issue and this is a high priority item and we want to get this deployed to prod as soon as we can but I have been blocked on this since very long.

Since support were not able to help me, can you please escalate this to next level?

Thanks,

Mounika Garlapati
.net Developer
    p: 312-379-2397
     f: 312-379-2397
***@***.******@***.***>
www.fidelitylife.com<http://www.fidelitylife.com>
***@***.***

**Comment by bryanapellanes-okta** [comment]
> Since support were not able to help me, can you please escalate this to next level?

Exploring options for you now.

**Comment by m-garlapati** [comment]
Thank you!

Mounika Garlapati
.net Developer
    p: 312-379-2397
     f: 312-379-2397
***@***.******@***.***>
www.fidelitylife.com<http://www.fidelitylife.com>
***@***.***

**Comment by bryanapellanes-okta** [comment]
@m-garlapati,
I'm following up with support; please provide the support ticket # that you opened for this.  I'll investigate further with support.

**Comment by bryanapellanes-okta** [comment]
@m-garlapati,
Because this issue is not caused by the Sdk, there is nothing we can do in this channel.  I'm working with support to determine how to move forward.

**Comment by m-garlapati** [comment]
Thank you! Support number 01188012

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bryanapellanes-okta** [comment]
Support will handle.
