### ISSUE TITLE
App fronted with LBP exposes app domain - fails to work

### ISSUE THREAD

**Issue by hmble2** [okta/okta-aspnet#186]
This library works just fine when app is not fronted by lbp.
Following setup works fine without any issues:
```
App URL https://my-app.xyz.com/process
RedirectUri: https://my-app.xyz.com/authorization-code/callback
```
However, when app is fronted by lbp then it fails:
```
App lbp URL: https://my-app.lbp.com/process
RedirectUri: https://my-app.lbp.com/authorization-code/callback
App direct URL: https://my-app.xyz.com/process
```
Since App is in cloud, lbp forwards request to cloud router with request 'Host' header set to my-app.xyz.com so that cloud router can route request to correct app container, while URI in browser stays https://my-app.lbp.com/process

In this situation, when logging for the first time, and after all redirects and successful authentication iscompleted, when final forward to https://app.lbp.com/authorization-code/callback happens ( by *.oktapreview.com) then this filter is sending 

```
HTTP 302 with incorrect domain (direct app domain) of https://my-app.xyz.com/process 
instead of correct domain (original lbp domain) https://my-app.lbp.com/process
```
I am thinking this is happening because filter redirecting to /process URL is using incoming request 'Host' header.

Could this be fixed?

**Comment by hmble2** [comment]
Thanks for getting back, could you please get this investigated. A possible solution: HTTP redirect using incoming HTTP Request LocalAddress Host (instead of 'Host' http request header) should resolve this issue, as incoming HTTP Request LocalAddress would be set to lbp host which is what is desirable with lbp and will continue to work in the absence of lbp.

**Comment by robertdamphousse-okta** [comment]
Hi @hmble2 , for this type of ticket, please submit a support case to developers@okta.com, that is a better channel to help you debug this level of application configuration.  For this repository, we focus on issues wit this SDK itself.
