### ISSUE TITLE
Authentication schemes supporting in extension methods

### ISSUE THREAD

**Issue by nivanov-stitan** [okta/okta-aspnet#191]
Hello. 
I am using this SDK to add MVC and WebApi authentication via Okta but extension methods (AddOktaMvc and AddOktaWebApi) from this SDK does not provide possibility to pass authentication schemes like standard microsoft extension methods (AddOpenIdConnect, AddJwtBearer). It is very useful to have this opportunity when you want to use multiple authentication schemes from multiple OKTA authorization servers.
Could you add authentication schemes for the extension methods?

**Comment by laura-rodriguez** [comment]
Hi @nivanov-stitan,

I transferred your issue to the right repo.

Would you mind posting what the configuration would look like for your use case? Also, can you give us more details about your use case? This will help us to understand your scenario better. Thanks!

**Comment by nivanov-stitan** [comment]
Hi @laura-rodriguez 
For instance, we have two API (API1 and API2) which protected by separate Authorization servers for each of them. Those APIs host in single web application. Also we have client applications which should have access to API1 or API2. To authorize clients web application should support both Okta authorization servers, which protects APIs.

**Comment by Tankatronic** [comment]
@laura-rodriguez 

We also could use this feature. In our use case, our company is a part of a larger organization and we are trying to allow API calls from a sister company that uses Okta as its authority while our APIs currently use IdentityServer for its authority. The desire was for an API to accept a bearer token both from Okta and IdentityServer, so we need to support multiple schemes for that. The scheme that Okta uses "bearer" is the same scheme that our system currently uses.

**Comment by laura-rodriguez** [comment]
@Tankatronic we merged your PR already (#205) and a [new package has been released](https://www.nuget.org/packages/Okta.AspNetCore/4.2.0). Thank you so much for your contribution! ⭐ 🎉 

Superseded by #205
