### ISSUE TITLE
Validating Access Token on ClientId

### ISSUE THREAD

**Issue by timsun4** [okta/okta-aspnet#194]
Hello,

I have a use case where there are multiple applications (.NET Core Web APIs) on the same domain. Since they are sharing a domain I have configured separate access policies for each application under a shared custom auth server. To prevent users from generating a valid token on one application and using it for another, I would like to validate the access token passed to my APIs. 

From what I can tell, the only difference between a valid and invalid access token for each application comes down to the 'cid'. However, per the documentation it seems like ClientId was removed as an option for OktaWebApiOptions a while back 
https://github.com/okta/okta-aspnet/blob/master/docs/aspnetcore-webapi.md#configuration-reference

Ideally we would like to subdomain each application and have separate custom auth servers set up, but is there any way to do this validation with our current configuration? Is there any potential for re-introducing ClientId as an optional parameter?

**Comment by bryanapellanes-okta** [comment]
@timsun4,
Thanks for reaching out!  Please provide a sample project/solution illustrating the proposed structure and desired API calls; we will need to review your request more closely to determine the best practice approach to accomplish your use case.  I've opened an internal item for tracking: OKTA-456050

**Comment by bryanapellanes-okta** [comment]
@timsun4,
Thank you for the additional details.  Please review the `introspect` endpoint documentation found here: https://developer.okta.com/docs/reference/api/oidc/#introspect.  This will provide additional details about a given token; will this help you to implement your use case?

**Comment by timsun4** [comment]
@bryanapellanes-okta 
Thanks for the link, tried a few requests to /introspect. 
It looks like if the provided client_id in the param does not match the client_id in the token then it returns "active": false. If they do match then "active": true. It appears that this does help us distinguish between valid/invalid tokens in our use case.

**Comment by bryanapellanes-okta** [comment]
@timsun4  Closing issue.  Feel free to open a new issue if you need help with anything else.
