### ISSUE TITLE
.NET integration returns empty claim

### ISSUE THREAD

**Issue by josepth30** [okta/okta-aspnet#196]
### Describe the bug?

Hello,

We have a problem with a .Net Framework integration with a self-hosted page. The problem we have is that after the user authenticates, it returns empty claims. I checked the configuration and everything is according to the documentation.

We are using a NetScaler to balance the traffic, the app is hosted on an IIS server, when we run it locally it works, but in IIS the user claim is empty.

This is the documentation we are using: https://developer.okta.com/docs/guides/sign-into-web-app/aspnet/main/#refresh-tokens-and-web-apps

thanks, best regards

### What is expected to happen?

Receive user information using claims after the user authenticates on the Okta self hosted page

### What is the actual behavior?

The /authorize api is consumed where the tokens are received but the user information is never received, the claims arrive empty

### Reproduction Steps?

I share har file with the test, please change the file extesion by .har
[HarHumanet10V2-PruebaClaimsCallback.txt](https://github.com/okta/okta-aspnet/files/7907981/HarHumanet10V2-PruebaClaimsCallback.txt)

### .NET Version

4.7.2

### SDK Version

4.0.0

**Comment by laura-rodriguez** [comment]
Hi @josepth30,

Thanks for your issue. Considering all the parts involved in your application (load balancers, IIS, Okta Org, etc) I suggest reaching out to support (developers@okta.com) so they can help you to debug your application.

**Comment by josepth30** [comment]
Thank you very much @laura-rodriguez. I going to send the issue to (developers@okta.com)

**Comment by laura-rodriguez** [comment]
Sounds good, feel free to reopen if it's applicable.

**Comment by josepth30** [comment]
Hello Lau.

I have had no response from the Okta developers. Could you help me with the problem?

Thanks

Regards.

**Comment by laura-rodriguez** [comment]
Hi @josepth30,

I apologize for the inconvenience. 
Let me try to reach out to the corresponding team for you.

Thanks,
