### ISSUE TITLE
Invalid NuGet dependencies results in immediate crash

### ISSUE THREAD

**Issue by qidydl** [okta/okta-aspnet#212]
### Describe the bug?

In the latest 4.2.0 release, Okta.AspNet.Abstractions [updated its dependency on System.IdentityModel.Tokens.Jwt](https://github.com/okta/okta-aspnet/compare/Okta.AspNetCore%404.1.0...Okta.AspNetCore%404.2.0#diff-ae7fbea8798f93e3d1d78bdaf026e08bdff4ae01ebf3e633985c6a0d51bc1978), but [no new package was released](https://www.nuget.org/packages/Okta.AspNet.Abstractions/). As a result, the dependencies declared by Okta do not match what Okta's code actually requires, so the Okta integration crashes immediately.

### What is expected to happen?

Okta.AspNet can be used at all.

### What is the actual behavior?

Okta.AspNet crashes immediately at runtime:

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=6.17.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'System.IdentityModel.Tokens.Jwt, Version=6.17.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
at Okta.AspNetCore.OktaAuthenticationOptionsExtensions.AddCodeFlow(AuthenticationBuilder builder, String authenticationScheme, OktaMvcOptions options)
at Okta.AspNetCore.OktaAuthenticationOptionsExtensions.AddOktaMvc(AuthenticationBuilder builder, OktaMvcOptions options)
```

Note that this version is what can be seen in `Okta.AspNet.Abstractions.csproj`, but because the [latest published version](https://www.nuget.org/packages/Okta.AspNet.Abstractions/4.0.0) states that only version 6.7.1 is required, .NET/NuGet can restore a version before 6.17.0 and then Okta crashes.

### Reproduction Steps?

Any and all use of Okta will produce this result.

### .NET Version

We're running on .NET 6.0.5.

### SDK Version

.NET 6.0.300

### OS version

AWS Lambda (I think that's Amazon Linux 2?)

**Comment by bryanapellanes-okta** [comment]
@qidydl,
Thanks for bringing this to our attention and I apologize for the inconvenience.  I've opened an internal ticket to address this: OKTA-501764

**Comment by laura-rodriguez** [comment]
Thanks @qidydl for reporting this! A new version was already released.
https://www.nuget.org/packages/Okta.AspNet.Abstractions/4.0.1

**Comment by qidydl** [comment]
Please note that just releasing a new version of Okta.AspNet.Abstractions didn't entirely fix this issue, because Okta.AspNet itself also needed to be updated to reference that new version of Okta.AspNet.Abstractions. However, this has now happened with Okta.AspNet version 3.0.1 and up, so the problem was actually resolved on July 13th and I can confirm it's no longer affecting us.
