### ISSUE TITLE
Proxy configuration not working ?

### ISSUE THREAD

**Issue by nicoduj** [okta/okta-aspnet#214]
### Describe the bug?

Hi,

We are testing Okta integration in our applications, and our component needs a corporate proxy to access the internet, otherwise we get the following error : 
> IDX20803: Unable to obtain configuration from ...

We tried the option mentionned in the doc : [https://github.com/okta/okta-aspnet/blob/master/docs/aspnet4x-mvc.md#proxy-configuration](Proxy configuration), but it did not work. We did not have any BackchannelHttpClientHandler defined.

The workaround we found was to use this BackchannelHttpClientHandler, and define our proxy in it : 

``
    public class Startup
    {

        public void Configuration(IAppBuilder app)
        {
            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);

            app.UseCookieAuthentication(new CookieAuthenticationOptions());

            var oktaOptions = new OktaMvcOptions()
            {
                OktaDomain = ConfigurationManager.AppSettings["okta:OktaDomain"],
                ClientId = ConfigurationManager.AppSettings["okta:ClientId"],
                ClientSecret = ConfigurationManager.AppSettings["okta:ClientSecret"],
                RedirectUri = ConfigurationManager.AppSettings["okta:RedirectUri"],
                PostLogoutRedirectUri = ConfigurationManager.AppSettings["okta:PostLogoutRedirectUri"],
                GetClaimsFromUserInfoEndpoint = true,
                Scope = new List<string> { "openid", "profile", "email" },
                BackchannelHttpClientHandler = new HttpClientHandlerProxy()
            };

            app.UseOktaMvc(oktaOptions);

        }
    }

    public class HttpClientHandlerProxy : DelegatingHandler
    {
        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            try
            {
                var uri = new Uri($"http://{ConfigurationManager.AppSettings["ProxyServer"]}");

                if (InnerHandler == null)
                {
                    base.InnerHandler = new HttpClientHandler()
                    {
                        Proxy = new WebProxy()
                        {
                            Address = uri,
                            BypassProxyOnLocal = true,
                        }
                    };
                }

                var response = await base.SendAsync(request, cancellationToken);
                return response;
            }
            catch (Exception ex)
            {
                throw;
            }
        }        
    }
``

### What is expected to happen?

We were excting to be able to use the proxy option defined in the documentation.

### What is the actual behavior?

It did not work, same behavior with it or without it.

### Reproduction Steps?

We simply add the option in the configuration, without any BackchannelHttpClientHandler , like this : 

No authentication defined (not needed), proxy server is on port 80.

``
public class Startup
{
    public void Configuration(IAppBuilder app)
    {
        app.UseOktaMvc(new OktaMvcOptions
        {
            // ... other configuration removed for brevity

            Proxy = new ProxyConfiguration
            {
                Host = "http://{yourProxyHostNameOrIp}",
                Port = 80, // Replace this value with the port that your proxy server listens on
            }
        });
    }
}
``

### Additional Information?

Deployed on IIS. Application pool v4.0

### .NET Version

MVC application.
Framework 4.7.03062

### SDK Version

Okta.AspNet 2.0.0
Okta.Aspnet.Abstractions 4.0.0

### OS version

BuildNumber  Caption                                 OSArchitecture  Version
9200         Microsoft Windows Server 2012 Standard  64 bits         6.2.9200

**Comment by laura-rodriguez** [comment]
Hi @nicoduj,

Thanks for reporting this issue. I'll file an internal ticket so our team can review and prioritize. In the meantime, it seems you found a valid workaround, right?

**Comment by nicoduj** [comment]
Hi,

Yes the workaround is ok for us I also noticed that our nugget is in 2.0, did not have time to check in 3.0 so might be good there. So no hurry on this, might also be because of our custom proxy / environment. I wanted to log it there with the workaround just in case !

**Comment by laura-rodriguez** [comment]
Sounds good! Let us know how it goes with 3.0.

**Comment by laura-rodriguez** [comment]
Fixed in 3.0.1
