### ISSUE TITLE
OpenIdConnect "OnRedirectToIdentityProvider" event with Custom Event Data not showing up in the Okta Widget on Okta Hosted Login Page

### ISSUE THREAD

**Issue by brentlyjdavid** [okta/okta-aspnet#216]
### Describe the bug?

Using the .AddOktaMvc method, we are trying to add custom properties to the request object in order to add a custom button in javascript on the okta hosted login page.  

Here is my event code:

```
.AddOktaMvc(new OktaMvcOptions()
{
  OktaDomain = settings.OktaDomain,
  ClientId = settings.OktaClientId,
  ClientSecret = settings.OktaClientSecret,
  Scope = settings.OktaScopes,
  GetClaimsFromUserInfoEndpoint = true,
  OpenIdConnectEvents = new OpenIdConnectEvents()
  {
      OnRedirectToIdentityProvider = context =>
      {
          context.Properties.Items.Add("productId", "12134");
          return Task.CompletedTask;
      }
  }
});
```

The problem is when I get to the Okta hosted login page, and use 

``` 
OktaUtil.getRequestContext();
```
The values I put into the property items array never show up anywhere to use.

### What is expected to happen?

I expect that when I add items to the request from the client app, that I can make decisions on these items on the hosted login page.

### What is the actual behavior?

No values show up anywhere in the request context.

### Reproduction Steps?

Use an okta sample, add custom items to the request in the event "OnRedirectToIdentityProvider" and see that in the Okta hosted login page, they are not available.

### .NET Version

6.0.301

### SDK Version

4.2.0

### OS version

```
BuildNumber  Caption                          OSArchitecture  Version
19044        Microsoft Windows 10 Enterprise  64-bit          10.0.19044
```

**Comment by brentlyjdavid** [comment]
Also, that productId is going to be dynamic, so a static URL won't work for us here.  We need to be able to add this item to the request and get it, so when we add a 'Register' button on the Okta Widget hosted by Okta, we can preserve the original productId they were attempting to get to.

**Comment by laura-rodriguez** [comment]
Hi @brentlyjdavid,

Thanks for reporting this. 

Would you mind sharing what `OktaUtil.getRequestContext();` looks like? We have an integration test that does something similar to what you wanna do, maybe you might wanna consider that approach?

* Set a custom property https://github.com/okta/okta-aspnet/blob/master/Okta.AspNetCore.Mvc.IntegrationTest/Startup.cs#L38

* Get custom property https://github.com/okta/okta-aspnet/blob/master/Okta.AspNetCore.Mvc.IntegrationTest/OktaMiddlewareShould.cs#L79

**Comment by brentlyjdavid** [comment]
Hi @laura-rodriguez 

To be clear, this problem is specific to getting the values back using the Okta Widget.  These custom values are only needed so we can use them to build a dynamic URL so we can add a 'register' button to the Okta Hosted Widget.  We want to maintain a product that they clicked on, normally we'd just use the query parameters, but they get hidden from us on the Okta Hosted page.  I'm assuming all the request information is hidden with an ID lookup or something on Okta's side.

I have omitted some token/id values and removed our tenant name for sake of public knowledge.
Here is what the JSON is when i make that `getRequestContext()` using the widget.  I was hoping in the 'authentication' => 'request' object that there would be an items array with my custom values.
```
{
  "target": {
    "clientId": "...",
    "name": "oidc_client",
    "links": {},
    "label": "Authentication User Portal OPENID",
    "type": {}
  },
  "authentication": {
    "request": {
      "scope": "openid profile",
      "response_type": "code",
      "state": "...",
      "redirect_uri": "https://localhost:44399/AuthenticationUserPortal/authorization-code/callback",
      "response_mode": "form_post"
    },
    "protocol": {},
    "amr": [],
    "client": {
      "name": "Authentication User Portal OPENID",
      "links": {},
      "id": "..."
    },
    "issuer": {
      "name": "default",
      "id": "...",
      "uri": "https://{oktadomain}/oauth2/default"
    }
  }
}
```

**Comment by laura-rodriguez** [comment]
Thanks for clarifying.  I believe this is a question for the SIW team. Basically, we need to know how you get custom properties that are being sent from the client. 

Do you have a Fiddler log that shows what the request to Okta looks like? Is the custom property being sent by the client? I can transfer your issue to the SIW repo if you confirm this.

**Comment by brentlyjdavid** [comment]
I will work on getting a log of some kind this morning.

**Comment by brentlyjdavid** [comment]
hi @laura-rodriguez  

Here is the URL that gets generated before Okta Hides it.  Some items omitted again for confidential/discoverability 

https://{oktaDomain}/oauth2/default/v1/authorize?client_id={clientId}&redirect_uri=https%3A%2F%2Flocalhost%3A44399%2FAuthenticationUserPortal%2Fauthorization-code%2Fcallback&response_type=code&scope=openid%20profile&code_challenge={codeChallenge}&code_challenge_method=S256&response_mode=form_post&nonce={nonce}&productId=1234&state={state}&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.10.0.0

Looks like productId is in the URL as we expect.  But when you call getRequestContext() there is no properties array, and since the URL gets hidden to just the root domain after the page is done loading, we can't inspect the URL.

I think it's safe to say the MVC SDK is sending what it's supposed to.  Can you forward this onto the other group that handles the widget?

**Comment by laura-rodriguez** [comment]
Thanks for checking @brentlyjdavid. I'll transfer your issue to the SIW repo.

**Comment by laura-rodriguez** [comment]
Sorry @brentlyjdavid, it seems I cannot transfer your issue to that specific repo. Can you please file a new issue [here](https://github.com/okta/okta-auth-js)? I'm gonna close this one.

**Comment by brentlyjdavid** [comment]
Yes, i just linked it to this one, i think it's ok to close here.
