### ISSUE TITLE
Login flow on Blazor Server Side broken with update to Okta.AspNetCore 4.4.1 from 4.4.0

### ISSUE THREAD

**Issue by fabiansanchez18** [okta/okta-aspnet#228]
### Describe the bug?

When trying to login in the openid flow from my page I get an "An unhandled exception occurred while processing the request."

Environment:
Blazor Server Side with Aspnetcore 6. 
on my Mac and also azure hosted page.

Exception Message:
"MissingMethodException: Method not found: 'Boolean Okta.AspNet.Abstractions.OktaParams.IsPromptEnrollAuthenticator(System.Collections.Generic.IDictionary`2<System.String,System.String>)'.
Okta.AspNetCore.OktaAuthenticationOptionsExtensions.BeforeRedirectToIdentityProviderAsync(RedirectContext context, Func<RedirectContext, Task> redirectEvent)"

Exception StackTrace Shown by the page:
"MissingMethodException: Method not found: 'Boolean Okta.AspNet.Abstractions.OktaParams.IsPromptEnrollAuthenticator(System.Collections.Generic.IDictionary`2<System.String,System.String>)'.
Okta.AspNetCore.OktaAuthenticationOptionsExtensions.BeforeRedirectToIdentityProviderAsync(RedirectContext context, Func<RedirectContext, Task> redirectEvent)
Okta.AspNetCore.OktaAuthenticationOptionsExtensions+<>c__DisplayClass4_0.<AddCodeFlow>b__0(RedirectContext context)
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectEvents.RedirectToIdentityProvider(RedirectContext context)
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
Microsoft.AspNetCore.Authentication.AuthenticationHandler<TOptions>.ChallengeAsync(AuthenticationProperties properties)
Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, string scheme, AuthenticationProperties properties)
Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)"

My code on program.cs configuring okta connection and flow:
`builder.Services.AddAuthentication(options =>
{
    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
})
.AddCookie()
.AddOktaMvc(new OktaMvcOptions
{
    // Replace the Okta placeholders in appsettings.json with your Okta configuration.
    OktaDomain = builder.Configuration.GetValue<string>("Okta:OktaDomain"),
    ClientId = builder.Configuration.GetValue<string>("Okta:ClientId"),
    ClientSecret = builder.Configuration.GetValue<string>("Okta:ClientSecret"),
    AuthorizationServerId = builder.Configuration.GetValue<string>("Okta:AuthorizationServerId"),
    Scope = new List<string> { "openid", "profile", "email" },
    OpenIdConnectEvents = new OpenIdConnectEvents
    {
        OnAuthenticationFailed = OnAuthenticationFailed,
        OnRemoteFailure = OnOktaApiFailure,
    },
});`

### What is expected to happen?

It was expected to login and follow the flow that takes the user to the okta widget on okta's servers to login users and then return to web page as usual.

### What is the actual behavior?

when I click the login button it throws the exception

### Reproduction Steps?

Configure a Blazor Server Side project and configure Okta login with openid for the widget on okta side with your official tutorial available when package version 4.4.0 was the latest.
All this done with package version 4.4.0.
Then update to version 4.4.1

### .NET Version

6.0.403

### SDK Version

6.0.403

### OS version

Darwin Homes-MacBook-Pro-2.local 20.6.0 Darwin Kernel Version 20.6.0: Thu Sep 29 20:15:11 PDT 2022; root:xnu-7195.141.42~1/RELEASE_X86_64 x86_64

And also on Azure Web Apps Service

**Comment by laura-rodriguez** [comment]
Hi @fabiansanchez18,

Thank you for reporting this issue. I'll file an internal ticket to be reviewed and prioritized by the team. 

Internal Ref: https://oktainc.atlassian.net/browse/OKTA-559644

**Comment by npalmer-zs** [comment]
Just wanted to add that I also encountered this issue on 4.4.1. Downgrading to 4.4.0 resolves the problem.

**Comment by vincentskooi** [comment]
Ah... encounter this error as well.. also downgrading to 4.4.0 and issue is not observed.

**Comment by Nelfff** [comment]
Same issue, downgrading Okta.AspNetCore to 4.4.0 resolves the issue.

**Comment by laura-rodriguez** [comment]
Fixed in:
Okta.AspNet.Abstractions v4.2.1
Okta.AspNet 3.2.2
Okta.AspNetCore v4.4.2
