### ISSUE TITLE
MissingMethodException after updating Okta.AspNet and Okta.AspNet.Abstractions on MVC project

### ISSUE THREAD

**Issue by longtriops** [okta/okta-aspnet#230]
### Describe the bug?

Method not found error when attempting to log in after updating to Okta.AspNet (3.2.1) and Okta.AspNet.Abstractions (4.2.0) through Visual Studio 2022 NuGet Package Manager. Cannot complete auth challenge/redirect to Okta.

**Server Error in '/' Application.**
Method not found: 'Boolean Okta.AspNet.Abstractions.OktaParams.IsPromptEnrollAuthenticator(System.Collections.Generic.IDictionary`2<System.String,System.String>)'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.MissingMethodException: Method not found: 'Boolean Okta.AspNet.Abstractions.OktaParams.IsPromptEnrollAuthenticator(System.Collections.Generic.IDictionary`2<System.String,System.String>)'.

**Source Error:**

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

**Stack Trace:**

[MissingMethodException: Method not found: 'Boolean Okta.AspNet.Abstractions.OktaParams.IsPromptEnrollAuthenticator(System.Collections.Generic.IDictionary`2<System.String,System.String>)'.]
   Okta.AspNet.OpenIdConnectAuthenticationOptionsBuilder.BeforeRedirectToIdentityProviderAsync(RedirectToIdentityProviderNotification`2 redirectToIdentityProviderNotification, Func`2 redirectEvent) +0
   Microsoft.Owin.Security.OpenIdConnect.<ApplyResponseChallengeAsync>d__10.MoveNext() in /_/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs:198
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Security.Infrastructure.<ApplyResponseCoreAsync>d__40.MoveNext() in /_/src/Microsoft.Owin.Security/Infrastructure/AuthenticationHandler.cs:179
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Security.Infrastructure.<ApplyResponseAsync>d__39.MoveNext() in /_/src/Microsoft.Owin.Security/Infrastructure/AuthenticationHandler.cs:167
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Security.Infrastructure.<TeardownAsync>d__34.MoveNext() in /_/src/Microsoft.Owin.Security/Infrastructure/AuthenticationHandler.cs:96
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__5.MoveNext() in /_/src/Microsoft.Owin.Security/Infrastructure/AuthenticationMiddleware.cs:32
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__7.MoveNext() in /_/src/Microsoft.Owin.Host.SystemWeb/IntegratedPipeline/IntegratedPipelineContextStage.cs:85
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__5.MoveNext() in /_/src/Microsoft.Owin.Security/Infrastructure/AuthenticationMiddleware.cs:30
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__7.MoveNext() in /_/src/Microsoft.Owin.Host.SystemWeb/IntegratedPipeline/IntegratedPipelineContextStage.cs:85
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__12.MoveNext() in /_/src/Microsoft.Owin.Host.SystemWeb/IntegratedPipeline/IntegratedPipelineContext.cs:153
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) in /_/src/Microsoft.Owin.Host.SystemWeb/IntegratedPipeline/StageAsyncResult.cs:76
   System.Web.AsyncEventExecutionStep.InvokeEndHandler(IAsyncResult ar) +184
   System.Web.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar) +115

### What is expected to happen?

app should redirect to okta-hosted login

### What is the actual behavior?

error occurs that prevents log in

### Reproduction Steps?

- download sample project from: https://github.com/okta/samples-aspnet
- open okta-hosted-login project
- update 
Okta.AspNet to version 3.2.1 
Okta.AspNet.Abstractions to version 4.2.0

- build and run project, click log in.

### .NET Version

$ dotnet --version
7.0.101

application type: MVC

### SDK Version

Okta.AspNet 3.2.1 
Okta.AspNet.Abstractions 4.2.0

### OS version

19044        
Microsoft Windows 10 Enterprise  64-bit          
10.0.19044

**Comment by laura-rodriguez** [comment]
Hi @longtriops,

Since you're using Okta.AspNet 3.2.1, you need to use an older version of Okta.AspNet.Abstractions or, alternatively, a newer version of Okta.AspNet.

**Comment by longtriops** [comment]
Hello, is there a newer version than Okta.AspNet 3.2.1? It looked like the latest version I could get, with the latest Okta.AspNet.Abstractions 4.2.0. Downgrading both resolved the issue, but the latest versions of each are not working together (in .net framework 4.8 project)

**Comment by laura-rodriguez** [comment]
Fixed in:
Okta.AspNet.Abstractions v4.2.1
Okta.AspNet 3.2.2
Okta.AspNetCore v4.4.2
