### ISSUE TITLE
Okta Widget + ASP.NET Core

### ISSUE THREAD

**Issue by justinhelgerson** [okta/okta-aspnet#25]
I haven't seen any documentation on how to use Okta on ASP.NET (Core or pre-Core) with a social IdP (Google, Facebook, etc).  Getting up and running with Okta via the OIDC middleware is a breeze, but it doesn't account for the social workflow as far as I can see.  In my scenario, I'd like to support Okta user account authentication in addition to social.

The [documentation](https://developer.okta.com/authentication-guide/social-login/google#using-google-for-login) makes it seem like you have to go down the path of using Javascript and building your own sign-in experience.  I have this workflow working in the sense that I can get JSON returned with an `id_token` and `claims`, but that doesn't hook into the ASP.NET security model very well (my app is not a SPA).

Is there a way to leverage the OIDC middleware with a social IdP workflow?

**Comment by nbarbettini** [comment]
Hey @justinhelgerson! This is a good question, sorry about the delayed response.

It is possible to get social login + ASP.NET Core working, although it isn't as straightforward as it should be (yet). We're still iterating on our .NET story and we need to do some more documentation here. I built a sample that might be helpful: https://github.com/nbarbettini/okta-aspnetcore-social-login-example
(The sample is older than this library, but the same pattern should work with this library too)

I'll leave this issue open to remind us that we need to add an official sample for this use case. Any feedback from your end is very helpful, thanks!

**Comment by justinhelgerson** [comment]
This example definitely helps, but I think the UX will be confusing for some of my customers.  It requires the user to make a choice (through links or buttons) between which login path to go down: Okta or IdP #1, #2, etc).  I think it would be more intuitive if there was a way to show the username and password inputs and then provide additional IdP paths (like the widget does).  I'm surprised the Okta hosted sign in page doesn't allow adding social IdP options.  It seems like that would cut out a lot of integration effort and integration mistakes.

The last thought I had... working within the confine of the widget, it seems like it could be possible to take the JWT and present it to a custom middleware (a hybrid of sort between the OIDC and JwtBearer middleware) that validates the token and performs cookie authentication.  I don't consider myself well-versed enough in OAuth/OIDC to build that and put in front of my users, but I would think that could be an option as well.

Anyway, thanks for the response.  Hopefully some of this feedback is useful.  I appreciate that you've got some public projects on GitHub; .NET is too often overlooked especially with the changes in the past few years.  Your OAuth presentation was great as well.

**Comment by justinhelgerson** [comment]
I updated the title of this issue to be a bit more targeted.  I think having an example of using the Okta Widget with ASP.NET Core is the real issue here.  Right now it's not possible to hook into the OIDC middleware of ASP.NET with the widget (correlation validation fails).

**Comment by nbarbettini** [comment]
Resurrecting this old thread since we published some new samples. Does this example cover the use case you were wondering about? https://github.com/okta/samples-aspnetcore/tree/master/self-hosted-login

**Comment by lelandroling** [comment]
I'm also attempting to use social logins with the Okta widget, then push to the ASP.NET Core backend. The only way I'm able to do this currently is by parsing the URL once the id token is return from the authorize endpoint and the redirect occurs. Is this how it was envisioned? It would be ideal to not pass this along in the URL and attempt to use a form post or some other kind of response mode.

I haven't found a single example that truly reflects turning on the social logins within the widget and then passing the id tokens to .NET Core.

**Comment by laura-rodriguez** [comment]
[self-hosted sample](https://github.com/okta/samples-aspnetcore/tree/master/self-hosted-login) shows how to hook into the OIDC middleware of ASP.NET with the widget.
