### ISSUE TITLE
Update ASP.NET quickstart with beta code

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-aspnet#26]
Update this quickstart: https://developer.okta.com/quickstart/#/okta-sign-in-page/dotnet/aspnet4
(Both the Sign-in Page and API versions)

- [ ] Demonstrate using the [Okta.AspNet package](https://www.nuget.org/packages/Okta.AspNet) package and new code (this will require the user to check **Include prerelease** or use `-pre` when installing)
- [ ] Include the below beta warning

> The [Okta.AspNet package](https://www.nuget.org/packages/Okta.AspNet) is currently in beta. We'd love to [get feedback](https://github.com/okta/okta-aspnet/issues/new) while we build the library. Until the library is stable, Okta doesn't recommend using it for production applications. Refer to the [sample app](https://github.com/oktadeveloper/okta-aspnet-mvc-example/) in the meantime for a supported way to get this working.

**Comment by laura-rodriguez** [comment]
Resolved by #34 & [#1967](https://github.com/okta/okta.github.io/pull/1967)
