### ISSUE TITLE
4.6.0 NET8 - IDX10500: Signature validation failed. No security keys were provided to validate the signature.

### ISSUE THREAD

**Issue by RichardBurns1982** [okta/okta-aspnet#261]
### Describe the bug?

We have OKTA integrated with our NET7 API, the configuration is quite basic:

```
services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = OktaDefaults.ApiAuthenticationScheme;
                options.DefaultChallengeScheme = OktaDefaults.ApiAuthenticationScheme;
                options.DefaultSignInScheme = OktaDefaults.ApiAuthenticationScheme;
            })
            .AddOktaWebApi(new OktaWebApiOptions
            {
                OktaDomain = "https://" + Configuration.GetValue<string>("Okta:Host"),
                Audience = Configuration.GetValue<string>("Okta:Claims:Audience"),
                AuthorizationServerId = Configuration.GetValue<string>("Okta:ServerId"),
                JwtBearerEvents = new JwtBearerEvents
                {
                    OnMessageReceived = context =>
                    {
                        var accessToken = context.Request.Query["access_token"];
                        var path = context.HttpContext.Request.Path;
                        if (!string.IsNullOrEmpty(accessToken) && path.StartsWithSegments("/hubs"))
                        {
                            context.Token = accessToken;
                        }

                        return Task.CompletedTask;
                    }
                }
            });
```

We have upgraded our application to NET8 and 4.6.0 and we are now receiving this:
 
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.

### What is expected to happen?

No changes, everything continues working.

### What is the actual behavior?

We can no longer login unless we downgrade to 4.5.0 of the aspnetcore package or implement the following:

```
var issuer = UrlHelper.CreateIssuerUrl(options.OktaDomain, options.AuthorizationServerId);

var configurationManager = new ConfigurationManager<OpenIdConnectConfiguration>(
  issuer + "/.well-known/oauth-authorization-server",
  new OpenIdConnectConfigurationRetriever(),
  new HttpDocumentRetriever()); 

 var tokenValidationParameters = new DefaultTokenValidationParameters(options, issuer)

 {
   SignatureValidator = (token, _) => ValidateTokenWithRetry(token, issuer, options.Audience)
 };
```

 

and then not using the AddOktaWebApi extension from the Okta libraries and calling AddJwtBearer directly setting TokenValidationParameters.

### Reproduction Steps?

Just use 4.6.0 on net8 with the standard AddOktaWebApi extension

### .NET Version

Web API NET8

### SDK Version

8.0.203

**Comment by laura-rodriguez** [comment]
Hi @RichardBurns1982 ,

Thanks for reporting this issue. This might be related to #260 and #259.

We're planning to work on a fix as soon as possible.

Thank you

**Comment by laura-rodriguez** [comment]
This should be fixed by #262. If the issue persists, please reopen the issue.

**Comment by jforage-sw** [comment]
No problem, thanks for the update @laura-rodriguez. We have a workaround for now

**Comment by pgates-brownadvisory** [comment]
I'm encountering this issue, too. Running .NET 8 and Okta.AspNetCore 4.6.1. Our usage is exactly the same as @jforage-sw 's minus the `JwtBearerEvents`.

**Comment by laura-rodriguez** [comment]
Hi @pgates-brownadvisory @jforage-sw, 
I'm not able to reproduce this issue. I've just tested it out with brand new .NET 7 Web API and .NET 8 Web API projects. Keys are retrieved in both cases using what's currently in the main branch (4.6.1). 
Can you please share a complete minimal project so I can plug my org details and try again? I wonder if when migrating an existing project to .NET8, some dependencies remain in a state that contributes to this issue 🤔 

Also, when does this error happen to you? When do you start the application or hit the protected endpoint?

**Comment by jforage-sw** [comment]
@laura-rodriguez Thanks for your response. Perhaps it would be easier if you share your working version first and then we can compare vs our own individual set ups? It will be hard to minimise our production environment into something shareable

**Comment by laura-rodriguez** [comment]
@jforage-sw good idea! Here's a temp repo with both repro projects.
https://github.com/laura-rodriguez/okta-webapi-repro-temp

**Comment by jforage-sw** [comment]
Thanks @laura-rodriguez I'll take a look and let you know how I get on

**Comment by pgates-brownadvisory** [comment]
> Thanks @laura-rodriguez I'll take a look and let you know how I get on
> 
> Looks like the repo is private. Please add me as a collaborator
> 
> @RichardBurns1982 FYI

@laura-rodriguez Please add me as a contributor too, if possible (and thanks, @jforage-sw for replying).

**Comment by laura-rodriguez** [comment]
@jforage-sw, the repo is public now; sorry about that.

**Comment by jforage-sw** [comment]
@laura-rodriguez Thanks, I can confirm your demo projects both work with our Okta auth server. Must be an issue our end, so will continue to investigate

**Comment by laura-rodriguez** [comment]
@jforage-sw ok, thanks for confirming. Please let us know how your investigation goes. Thanks!

**Comment by jforage-sw** [comment]
@laura-rodriguez OK, I have this working now on our end too. It required explicitly downgrading the following packages to v7.1.2 to match that of the versions referenced in Okta.AspNetCore v4.6.1:

- Microsoft.IdentityModel.JsonWebTokens
- System.IdentityModel.Tokens.Jwt

Thanks for your help resolving this issue for us

**Comment by RichardBurns1982** [comment]
@laura-rodriguez Do you know when you will be upgrading the Okta SDK to the latest versions as this leaves us locked to older packages.

**Comment by laura-rodriguez** [comment]
Hey @RichardBurns1982 , can you be more specific about what latest versions you're referring to? Thank you
