### ISSUE TITLE
Update ASP.NET Core quickstart with beta code

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-aspnet#27]
Update this quickstart: https://developer.okta.com/quickstart/#/okta-sign-in-page/dotnet/aspnetcore
(Both the Sign-in Page version and API version)

- [ ] Demonstrate using the [Okta.AspNet package](https://www.nuget.org/packages/Okta.AspNetCore) package and new code (this will require the user to check **Include prerelease** or use `-pre` when installing)
- [ ] Include the below beta warning

> The [Okta.AspNetCore package](https://www.nuget.org/packages/Okta.AspNetCore) is currently in beta. We'd love to [get feedback](https://github.com/okta/okta-aspnet/issues/new) while we build the library. Until the library is stable, Okta doesn't recommend using it for production applications. Refer to the [sample app](https://github.com/oktadeveloper/okta-aspnetcore-mvc-example/) in the meantime for a supported way to get this working.

**Comment by laura-rodriguez** [comment]
Resolved by #34 & [#2048](https://github.com/okta/okta.github.io/pull/2048)
