### ISSUE TITLE
Add CustomAuthPage Url as a option. 

### ISSUE THREAD

**Issue by coreyperkins** [okta/okta-aspnet#31]
After working with Okta via the standard OWIN middleware (not this repo) I noticed that the asp.net/OWIN way of redirecting to a custom authentication page is rather heinous. It requires tinkering with the Cookie and OIDC middleware bits, including AuthenticationMode, etc...all just to redirect to a different domain/url.

As a convenience for developers (who don't like writing excess c# to do a simple task) adding CustomAuthPageUrl (or some variation of) could be extremely helpful. Thanks!

**Comment by justinhelgerson** [comment]
@coreyperkins Could you share some more details about what you were looking to achieve here?  Describing the flow of events could be helpful.

I'm not affiliated with Okta, but I also ended up hacking the ASP.NET middleware a bit to get my UX right.  I was considering building a proper middleware for my scenario, so I'm curious what you were doing.

**Comment by nbarbettini** [comment]
I'm also curious about both of your use cases. Mind answering a few questions? Or, if you shoot me an email at nate.barbettini@okta.com I'd love to set up a quick 15-minute call to pick your brain.

* Why do you need a custom login page?
* Is there a reason you can't customize the Okta-hosted login page enough for your needs?
* What hacking did you have to do at the middleware layer to get this to work?

We are definitely going to add some features to this library to make it easier to build custom login pages. Before we do, I want to make sure we are capturing the use cases correctly. 👍

**Comment by coreyperkins** [comment]
@justinhelgerson Absolutely! We have several applications (of varying tech, ASP.NET, NodeJS, etc) that authenticate through Okta. Currently we are using the Okta-hosted login page with a small hack in place to make sure when it is used from a calling app we get redirected back to the right application. We literally just added a redirect parameter onto the Okta-hosted login page (customauthdomain.com?redirect=https://callingaappredirecturi. This works, but only when our applications are allowed to be configured to go through a custom page easily, this is not the case for ASP.NET apps currently.

I did something very similar to this (https://stackoverflow.com/questions/21275399/login-page-on-different-domain) to try and provide a custom url in the ASP.NET scenario, but it led me down a rabbit hole that I didn't care much for because once you turn one piece of OWIN middleware to AuthenticationMode = Active that unhooks several messages that you then have to handled on your own. Since our hacked up "redirect" simply does a location.href inside the Okta-hosted login page, no dice. We also went down this road because the Okta-hosted login page did not support redirecting back to the calling application when using Google or Microsoft auth, as most of our users do.

With this small hack in place, we sorta get the behavior we want, but it has shows us some flaws in our workflow. Such as if you don't auth through our custom page you do not get redirected back properly.

@nbarbettini 

Answers to your questions.

1. We ran into trouble with the Okta-hosted login page with authentication with Microsoft or Google. It would work fine with Okta logins but with M$ or Google it will simple redirect back to the login page and not to the calling application. One of our PMs contacted Okta support, but we were not presented with how to go about accomplishing this correctly in the Okta-hosted login page.

2. That would be fantastic. Here is what we've tried so far, but it is flawed because of what I mentioned previously (if you don't auth with the redirect hack in place you won't get redirected to the proper location. We think there is probably a way to configure the Okta-hosted login page to behave accordingly, but we have not been able to learn enough about the Okta js libs to make it happen on our own yet. Here are the changes we've attempted so far, but they have caused problems.

		oktaSignIn.renderEl({ el: '#okta-login-container' },
  			function (res) {
                             try {
                	                 var redirect = location.search.split('redirect=')[1];
                                  location.href = redirect;
                                  OktaUtil.completeLogin();
                             } catch (redirectErr) {
                	                 console.log(redirectErr);  
                                  OktaUtil.completeLogin();
                         }
  			},
  			function (error) {
    			// Logs errors that occur when configuring the widget.
    			// Remove or replace this with your own custom error handler.
    			console.log(error.message, error);
  			}
		);

We feel like if we knew more we could utilize the Okta libraries to handle the redirect of the calling app w/o having to manually attach it, but we are not certain how to go about that currently.

3. Hacking the ASP.NET middleware did not get us the results we were hoping for because of the reasons mentioned above to @justinhelgerson

@nbarbettini I'd be very interested in a chat, you can reach me at corey.perkins@agconnections.com.

Thanks guys!

Corey

**Comment by coreyperkins** [comment]
Just a note, we've moved to a login page per app now in order to get around the issues mentioned above. This is working for us, but we would like to be able to use the Okta-hosted login page if it is updated to handle our scenario. We'd be fine using a central login page we host ourselves, too, if that becomes an option later with this project.

**Comment by justinhelgerson** [comment]
@nbarbettini This is a super late response.  Long story short I wasn't sure if we were going to become an Okta customer or not so I didn't want to chew up your time.  Now that we are officially moving forward with Okta, I'll come back to this and provide some details on why the Okta hosted page wasn't working for us.
