### ISSUE TITLE
Add Support for multiple client id validation in StrictTokenHandler

### ISSUE THREAD

**Issue by dancarlstedt** [okta/okta-aspnet#46]
I would like to use this nuget package to hookup my Web API, however my API serves multiple clients and this middleware will only allow for a single client to be used because of the [StrictTokenHandler.cs](https://github.com/okta/okta-aspnet/blob/master/Okta.AspNet.Abstractions/StrictTokenHandler.cs) validation. 

``` csharp
app.UseOktaWebApi(new OktaWebApiOptions()
            {
                OktaDomain = "https://<mydomain>",
                ClientId = "myclientid",       // I need a way to pass in multiple client ids here
                AuthorizationServerId = "myauthserverid"
            });
```

I would like to propose either of the following options:
- change `ClientId` to an array so it can hold a whitelist of client ids that can be validated in the [StrictTokenHandler.cs](https://github.com/okta/okta-aspnet/blob/master/Okta.AspNet.Abstractions/StrictTokenHandler.cs) 
- allow for injection of another custom TokenHandler via the `OktaWebApiOptions`

**Comment by nbarbettini** [comment]
Hey @dancarlstedt! Thanks for the well-described feature request.

This is something we are working on already. Are you okay to wait for our next minor release?

**Comment by dancarlstedt** [comment]
Hey @nbarbettini. Yes we can wait until after the next minor release. Do you mind sharing how you will be supporting this scenario? White list or Injecting something? Or something different all together.

**Comment by nbarbettini** [comment]
@dancarlstedt Hey, sorry for the delay. We will be supporting this scenario by dropping client ID validation from `StrictTokenHandler`. The audience check will still happen, but we don't want to force resource servers to whitelist clients.

**Comment by jharoutuniand2l** [comment]
Hey @nbarbettini - I am also very interested in this feature 👍  
Is there any rough timeline for the next minor release?
Thanks!

**Comment by laura-rodriguez** [comment]
Hi @jharoutuniand2l,
We have prioritized this issue for our next sprint. It's going to be released in a couple of days. Stay tuned!
