### ISSUE TITLE
SignOutResult() Invalid_token Error

### ISSUE THREAD

**Issue by thecoops** [okta/okta-aspnet#70]
My application was working fine using the Okta.AspNetCore v 1.1.4 middleware.  When I updated it to version 1.1.5, my app started throwing a 400 bad request error in the following line of code while logging out:

`return new SignOutResult(new[]
            {
                OktaDefaults.MvcAuthenticationScheme,
                CookieAuthenticationDefaults.AuthenticationScheme
            });`

I rolled the NuGet package back to version 1.1.4 and everything is working again.

![Screenshot - %y%m%d 922](https://user-images.githubusercontent.com/25965782/55017775-d0b32b80-4fc7-11e9-80be-0638bbf51127.png)

**Comment by laura-rodriguez** [comment]
Hi @thecoops!
Sorry about the inconvenience. 
I want to double check a few things:
* Are you using one of our [samples](https://github.com/okta/samples-aspnetcore)? 
* Are you using the Okta-hosted login page or the self-hosted in your application?
* Do you have a `PostLogoutRedirectUri` set?

**Comment by thecoops** [comment]
> Hi @thecoops!
> Sorry about the inconvenience.
> I want to double check a few things:
> 
> * Are you using one of our [samples](https://github.com/okta/samples-aspnetcore)?
> * Are you using the Okta-hosted login page or the self-hosted in your application?
> * Do you have a `PostLogoutRedirectUri` set?

No, I'm not running one of your samples, but, I did base our code off the quick start guide.  We've built our own web application.
We are using the Okta-hosted login page.
Yes, our "PostLogoutRedirectUri" is set to `https://localhost:44319/signout/callback`

**Comment by thecoops** [comment]
The error is getting trapped at line #195 of:

> https://{domain}.okta.com/oauth2/default/v1/logout?post_logout_redirect_uri=https://localhost:44319/signout/callback&state={our_state}&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.3.0.0

Sorry, that's about all I can help with...

**Comment by laura-rodriguez** [comment]
Hi @thecoops,

 Apologies that we haven't followed up yet! Are you still facing this issue?

**Comment by thecoops** [comment]
I rolled back to the previous version and everything works fine. Haven’t tried the newer version again.

Mike

On May 17, 2019, at 4:38 PM, Laura Rodríguez <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @thecoops<https://github.com/thecoops>,

Apologies that we haven't followed up yet! Are you still facing this issue?

**Comment by jaikeshsinghgithub** [comment]
Hi

I am trying with sample app. But still getting 404 Invalid_token Error. I switched back to Okta.AspNetCore 1.1.4, but still getting the same error

gsalunkhe

**Comment by gsalunkhe** [comment]
> Hi @thecoops!
> Sorry about the inconvenience.
> I want to double check a few things:
> 
> * Are you using one of our [samples](https://github.com/okta/samples-aspnetcore)?
> * Are you using the Okta-hosted login page or the self-hosted in your application?
> * Do you have a `PostLogoutRedirectUri` set?

Hi @laura-rodriguez 

I tried with sample given,  okta-hosted-login. But getting same error. Can you tell to which all paces I should check for.

Thanks
gsalunkhe

**Comment by laura-rodriguez** [comment]
Hi @gsalunkhe,

Sorry for the inconvenience. This error can be related to your configuration. 
I would like to check a few things:

* Are you using ASP.NET core or 4.x?
* Are you using a custom Authorization Server? (Have you assigned a value diff to the default one to the AuthorizationServerId property?)
* Can you post your Okta configuration? Make sure to not post your secrets.

Thanks!

**Comment by gsalunkhe** [comment]
Hi @laura-rodriguez 

Please find answers below

- Are you using ASP.NET core or 4.x?

     I am using .NET core 2.1

- Are you using a custom Authorization Server? (Have you assigned a value diff to the default one to the AuthorizationServerId property?)

     Can you please explain more, I didn't understand the details.

- Can you post your Okta configuration? Make sure to not post your secrets.

3) Okta configurations are

  "Okta": {
    "OktaDomain": "https://biorad-ext.okta.com",
    "ClientId": "XXXXXXXXXXX",
    "ClientSecret": "XXXXXXXXXXXXXX",
    "post_logout_redirect_uri": "http://localhost:49606"
    "CallBack": "http://localhost:49606/signout/callback"
  }

Thanks

**Comment by laura-rodriguez** [comment]
There's no need for you to set `post_logout_redirect_uri` or `callback` in your Okta ASP.NET Core configuration. But you have to whitelist those values in your Okta App in your Dev Console. We have step-by-step instructions to sign users out of your application and Okta. 
Please take a look at this guide: https://developer.okta.com/docs/guides/sign-users-out/aspnetcore/sign-out-of-okta/.

Let me know if it helps.

**Comment by gsalunkhe** [comment]
Hi @laura-rodriguez 

Thanks for your help

I need to add  options.SaveTokens = true;  to startup.cs.

Thanks
gsalunkhe

**Comment by laura-rodriguez** [comment]
Hi @gsalunkhe, 
I'm glad you fixed it. 
I'm curious, are you using the Okta ASP.NET SDK or the OIDC middleware? 
In the Okta ASP.NET SDK that configuration is already set: https://github.com/okta/okta-aspnet/blob/master/Okta.AspNetCore/OpenIdConnectOptionsHelper.cs#L35.
