### ISSUE TITLE
RedirectUri property missing from Okta.AspNetCore package

### ISSUE THREAD

**Issue by insideou7** [okta/okta-aspnet#85]
I need to set the RedirectUri because my app is running behind a virtual directory. Setting that up locally in Core is a bit messy right now, so it might not be configured somewhere it needs to be. In any case Okta is taking http://localhost/MyApp and turning the RedirectUri to just http://localhost. I'm guessing this would affect apps behind a proxy as well.

**Comment by laura-rodriguez** [comment]
Hi @insideou7 ,
You can use the `CallbackPath` property : https://github.com/okta/okta-aspnet/blob/master/Okta.AspNetCore/OktaMvcOptions.cs#L31.

We need to update the README since it's referring to `RedirectUri` instead of `CallbackPath`.
