### ISSUE TITLE
Code examples not working - OktaDomain not being picked up in settings files

### ISSUE THREAD

**Issue by jabil-rg02** [okta/okta-aspnet#87]
We've decided to put Okta support on hold.  I could not find any AspNetCore projects or MVC 5 code examples on GitHub repository that work and no response from support.

Test Name:	Okta.AspNetCore.Mvc.IntegrationTest.MiddlewareShould.RedirectWhenAccessToProtectedRouteWithoutSignedInAsync
Test FullName:	Okta.AspNetCore.Mvc.IntegrationTest.MiddlewareShould.RedirectWhenAccessToProtectedRouteWithoutSignedInAsync
Test Source:	C:\Users\jabil.100004892\okta-aspnet\Okta.AspNetCore.Mvc.IntegrationTest\MiddlewareShould.cs : line 41
Test Outcome:	Failed
Test Duration:	0:00:00.001

Result StackTrace:	
at Okta.AspNet.Abstractions.OktaWebOptionsValidator`1.Validate(OktaWebOptions options) in C:\Users\jabil.100004892\okta-aspnet\Okta.AspNet.Abstractions\OktaWebOptionsValidator.cs:line 33
   at Okta.AspNetCore.OktaAuthenticationOptionsExtensions.AddOktaMvc(AuthenticationBuilder builder, OktaMvcOptions options) in C:\Users\jabil.100004892\okta-aspnet\Okta.AspNetCore\OktaAuthenticationOptionsExtensions.cs:line 25
   at Okta.AspNetCore.Mvc.IntegrationTest.Startup.ConfigureServices(IServiceCollection services) in C:\Users\jabil.100004892\okta-aspnet\Okta.AspNetCore.Mvc.IntegrationTest\Startup.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at Okta.AspNetCore.Mvc.IntegrationTest.MiddlewareShould..ctor() in C:\Users\jabil.100004892\okta-aspnet\Okta.AspNetCore.Mvc.IntegrationTest\MiddlewareShould.cs:line 32
Result Message:	
System.ArgumentNullException : Your Okta URL is missing. You can copy your domain from the Okta Developer Console. Follow these instructions to find it: https://bit.ly/finding-okta-domain
Parameter name: OktaDomain

![error_aspnetcore](https://user-images.githubusercontent.com/25590697/61175543-674f2c80-a566-11e9-8155-5fa1f011642c.png)

**Comment by laura-rodriguez** [comment]
Hi @jabil-rg02,
We apologize for the inconvenience. The Configuration object maps configuration from different providers (i.e Env Vars, JSON files, etc). Maybe your `appsettings.json` is being overwritten by something else. Can you debug the following code in your `Startup` class to verify what is mapped to your Okta values? 
```
   .AddOktaMvc(new OktaMvcOptions
            {
                // Replace these values with your Okta configuration
                OktaDomain = Configuration.GetValue<string>("Okta:OktaDomain"),
                ClientId = Configuration.GetValue<string>("Okta:ClientId"),
                ClientSecret = Configuration.GetValue<string>("Okta:ClientSecret"),
            });
```
https://github.com/okta/samples-aspnetcore/blob/master/okta-hosted-login/okta-aspnetcore-mvc-example/Startup.cs#L43.

Also, as a workaround, you can try to assign those values directly in the `Startup` class:

![image](https://user-images.githubusercontent.com/16751130/61229117-8c25da00-a6f5-11e9-89d0-bd3507f111f8.png)

In case you don't know, you can test common scenarios quickly with our ASP.NET samples:

* https://github.com/okta/samples-aspnetcore
* https://github.com/okta/samples-aspnet
* https://github.com/okta/samples-aspnet-webforms

I hope this helps.

**Comment by jabil-rg02** [comment]
I wasn't able to get that example working. I modified the Visual Studio template to work with Okta defaults and provided some screen shots on the readme.md.  Feel free to pull the code example and use, I've checked it in to github for our purposes.

Thank You!

**Comment by laura-rodriguez** [comment]
Hi @jabil-rg02 ,

Have you tried to assign those values directly as I showed you above?

Not sure if the secrets you've posted in the `appsettings` file in the PR are the ones you are using now, but if so, I highly recommend you to invalidate them. As apparently is the `OktaDomain` which is failing there's no need to test it with valid client id/secret :).

I've pulled your PR but it has multiple compiling errors. I recommend you to test this using one of our ASP.NET samples instead of the IT projects we have in the ASP.NET solution. Keep it simple, you can remove all the Azure code for now, to narrow down the issue. 

I'd be happy to review this again & help you fixing this issue.

**Comment by laura-rodriguez** [comment]
Also, can you give more background of how is your Login flow?

**Comment by jabil-rg02** [comment]
I included screenshots in the pull request.   The readme file shows all the Okta settings and the code example running
