### ISSUE TITLE
How to validate access tokens against expiration time

### ISSUE THREAD

**Issue by kedar9444** [okta/okta-aspnet#94]
How to validate tokens against expiration time in .net core.

**Comment by laura-rodriguez** [comment]
Hi @kedar9444 ,

Can you give me more information about your use case? 
Is it an MVC application or a WEB API?

**Comment by kedar9444** [comment]
its .net core webapi application which receives token from angular app.

**Comment by laura-rodriguez** [comment]
Hi @kedar9444 ,

Sorry we haven't followed up yet!

We already validate the expiration time in Web API. We use the [`DefaultTokenValidationParameters`](https://github.com/okta/okta-aspnet/blob/master/Okta.AspNet.Abstractions/DefaultTokenValidationParameters.cs#L14), which has `RequireExpirationTime = true`.

Isn't it working for you?

**Comment by laura-rodriguez** [comment]
Closed due to inactivity.
